// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ChainItem chain item
//
// swagger:model chainItem
type ChainItem struct {

	// block time seconds
	// Example: 12
	BlockTimeSeconds int64 `json:"block_time_seconds,omitempty"`

	// chain id
	// Example: 1
	// Required: true
	ChainID *int64 `json:"chain_id"`

	// chain name
	// Example: Ethereum Mainnet
	// Required: true
	ChainName *string `json:"chain_name"`

	// chain type
	// Example: evm
	// Required: true
	ChainType *string `json:"chain_type"`

	// confirmation blocks
	// Example: 12
	ConfirmationBlocks int64 `json:"confirmation_blocks,omitempty"`

	// finalized blocks
	// Example: 32
	FinalizedBlocks int64 `json:"finalized_blocks,omitempty"`

	// id
	// Example: 1
	// Required: true
	ID *int64 `json:"id"`

	// is active
	// Example: true
	// Required: true
	IsActive *bool `json:"is_active"`

	// native token symbol
	// Example: ETH
	// Required: true
	NativeTokenSymbol *string `json:"native_token_symbol"`
}

// Validate validates this chain item
func (m *ChainItem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChainID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateChainName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateChainType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateIsActive(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNativeTokenSymbol(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ChainItem) validateChainID(formats strfmt.Registry) error {

	if err := validate.Required("chain_id", "body", m.ChainID); err != nil {
		return err
	}

	return nil
}

func (m *ChainItem) validateChainName(formats strfmt.Registry) error {

	if err := validate.Required("chain_name", "body", m.ChainName); err != nil {
		return err
	}

	return nil
}

func (m *ChainItem) validateChainType(formats strfmt.Registry) error {

	if err := validate.Required("chain_type", "body", m.ChainType); err != nil {
		return err
	}

	return nil
}

func (m *ChainItem) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	return nil
}

func (m *ChainItem) validateIsActive(formats strfmt.Registry) error {

	if err := validate.Required("is_active", "body", m.IsActive); err != nil {
		return err
	}

	return nil
}

func (m *ChainItem) validateNativeTokenSymbol(formats strfmt.Registry) error {

	if err := validate.Required("native_token_symbol", "body", m.NativeTokenSymbol); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this chain item based on context it is used
func (m *ChainItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *ChainItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ChainItem) UnmarshalBinary(b []byte) error {
	var res ChainItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
