// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CollectItem collect item
//
// swagger:model collectItem
type CollectItem struct {

	// amount
	// Example: 1.5
	// Required: true
	Amount *string `json:"amount"`

	// block no
	// Example: 12345678
	// Required: true
	BlockNo *int64 `json:"block_no"`

	// chain id
	// Example: 1
	// Required: true
	ChainID *int64 `json:"chain_id"`

	// confirmation count
	// Example: 5
	ConfirmationCount int64 `json:"confirmation_count,omitempty"`

	// created at
	// Required: true
	// Format: date-time
	CreatedAt *strfmt.DateTime `json:"created_at"`

	// from addr
	// Example: 0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b6
	// Required: true
	FromAddr *string `json:"from_addr"`

	// id
	// Required: true
	// Format: uuid
	ID *strfmt.UUID `json:"id"`

	// status
	// Example: confirmed
	// Required: true
	// Enum: [confirmed safe finalized failed]
	Status *string `json:"status"`

	// to addr
	// Example: 0x8ba1f109551bD432803012645Hac136c22C177E7
	// Required: true
	ToAddr *string `json:"to_addr"`

	// tx hash
	// Example: 0x...
	// Required: true
	TxHash *string `json:"tx_hash"`
}

// Validate validates this collect item
func (m *CollectItem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBlockNo(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateChainID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFromAddr(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateToAddr(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTxHash(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CollectItem) validateAmount(formats strfmt.Registry) error {

	if err := validate.Required("amount", "body", m.Amount); err != nil {
		return err
	}

	return nil
}

func (m *CollectItem) validateBlockNo(formats strfmt.Registry) error {

	if err := validate.Required("block_no", "body", m.BlockNo); err != nil {
		return err
	}

	return nil
}

func (m *CollectItem) validateChainID(formats strfmt.Registry) error {

	if err := validate.Required("chain_id", "body", m.ChainID); err != nil {
		return err
	}

	return nil
}

func (m *CollectItem) validateCreatedAt(formats strfmt.Registry) error {

	if err := validate.Required("created_at", "body", m.CreatedAt); err != nil {
		return err
	}

	if err := validate.FormatOf("created_at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *CollectItem) validateFromAddr(formats strfmt.Registry) error {

	if err := validate.Required("from_addr", "body", m.FromAddr); err != nil {
		return err
	}

	return nil
}

func (m *CollectItem) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	if err := validate.FormatOf("id", "body", "uuid", m.ID.String(), formats); err != nil {
		return err
	}

	return nil
}

var collectItemTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["confirmed","safe","finalized","failed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		collectItemTypeStatusPropEnum = append(collectItemTypeStatusPropEnum, v)
	}
}

const (

	// CollectItemStatusConfirmed captures enum value "confirmed"
	CollectItemStatusConfirmed string = "confirmed"

	// CollectItemStatusSafe captures enum value "safe"
	CollectItemStatusSafe string = "safe"

	// CollectItemStatusFinalized captures enum value "finalized"
	CollectItemStatusFinalized string = "finalized"

	// CollectItemStatusFailed captures enum value "failed"
	CollectItemStatusFailed string = "failed"
)

// prop value enum
func (m *CollectItem) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, collectItemTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *CollectItem) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", *m.Status); err != nil {
		return err
	}

	return nil
}

func (m *CollectItem) validateToAddr(formats strfmt.Registry) error {

	if err := validate.Required("to_addr", "body", m.ToAddr); err != nil {
		return err
	}

	return nil
}

func (m *CollectItem) validateTxHash(formats strfmt.Registry) error {

	if err := validate.Required("tx_hash", "body", m.TxHash); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this collect item based on context it is used
func (m *CollectItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CollectItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CollectItem) UnmarshalBinary(b []byte) error {
	var res CollectItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
