// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// DepositItem deposit item
//
// swagger:model depositItem
type DepositItem struct {

	// amount
	// Example: 1000000000000000000
	// Required: true
	Amount *string `json:"amount"`

	// block no
	// Example: 12345678
	// Required: true
	BlockNo *int64 `json:"block_no"`

	// chain id
	// Example: 1
	// Required: true
	ChainID *int64 `json:"chain_id"`

	// confirmation count
	// Example: 32
	ConfirmationCount int64 `json:"confirmation_count,omitempty"`

	// created at
	// Example: 2025-01-01T00:00:00Z
	// Required: true
	// Format: date-time
	CreatedAt *strfmt.DateTime `json:"created_at"`

	// from addr
	// Example: 0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b6
	// Required: true
	FromAddr *string `json:"from_addr"`

	// id
	// Required: true
	// Format: uuid
	ID *strfmt.UUID `json:"id"`

	// status
	// Example: finalized
	// Required: true
	// Enum: [confirmed safe finalized failed]
	Status *string `json:"status"`

	// to addr
	// Example: 0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b6
	// Required: true
	ToAddr *string `json:"to_addr"`

	// token addr
	// Example: 0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b6
	TokenAddr string `json:"token_addr,omitempty"`

	// token symbol
	// Example: ETH
	// Required: true
	TokenSymbol *string `json:"token_symbol"`

	// tx hash
	// Example: 0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef
	// Required: true
	TxHash *string `json:"tx_hash"`
}

// Validate validates this deposit item
func (m *DepositItem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBlockNo(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateChainID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCreatedAt(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFromAddr(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStatus(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateToAddr(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTokenSymbol(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTxHash(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *DepositItem) validateAmount(formats strfmt.Registry) error {

	if err := validate.Required("amount", "body", m.Amount); err != nil {
		return err
	}

	return nil
}

func (m *DepositItem) validateBlockNo(formats strfmt.Registry) error {

	if err := validate.Required("block_no", "body", m.BlockNo); err != nil {
		return err
	}

	return nil
}

func (m *DepositItem) validateChainID(formats strfmt.Registry) error {

	if err := validate.Required("chain_id", "body", m.ChainID); err != nil {
		return err
	}

	return nil
}

func (m *DepositItem) validateCreatedAt(formats strfmt.Registry) error {

	if err := validate.Required("created_at", "body", m.CreatedAt); err != nil {
		return err
	}

	if err := validate.FormatOf("created_at", "body", "date-time", m.CreatedAt.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *DepositItem) validateFromAddr(formats strfmt.Registry) error {

	if err := validate.Required("from_addr", "body", m.FromAddr); err != nil {
		return err
	}

	return nil
}

func (m *DepositItem) validateID(formats strfmt.Registry) error {

	if err := validate.Required("id", "body", m.ID); err != nil {
		return err
	}

	if err := validate.FormatOf("id", "body", "uuid", m.ID.String(), formats); err != nil {
		return err
	}

	return nil
}

var depositItemTypeStatusPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["confirmed","safe","finalized","failed"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		depositItemTypeStatusPropEnum = append(depositItemTypeStatusPropEnum, v)
	}
}

const (

	// DepositItemStatusConfirmed captures enum value "confirmed"
	DepositItemStatusConfirmed string = "confirmed"

	// DepositItemStatusSafe captures enum value "safe"
	DepositItemStatusSafe string = "safe"

	// DepositItemStatusFinalized captures enum value "finalized"
	DepositItemStatusFinalized string = "finalized"

	// DepositItemStatusFailed captures enum value "failed"
	DepositItemStatusFailed string = "failed"
)

// prop value enum
func (m *DepositItem) validateStatusEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, depositItemTypeStatusPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *DepositItem) validateStatus(formats strfmt.Registry) error {

	if err := validate.Required("status", "body", m.Status); err != nil {
		return err
	}

	// value enum
	if err := m.validateStatusEnum("status", "body", *m.Status); err != nil {
		return err
	}

	return nil
}

func (m *DepositItem) validateToAddr(formats strfmt.Registry) error {

	if err := validate.Required("to_addr", "body", m.ToAddr); err != nil {
		return err
	}

	return nil
}

func (m *DepositItem) validateTokenSymbol(formats strfmt.Registry) error {

	if err := validate.Required("token_symbol", "body", m.TokenSymbol); err != nil {
		return err
	}

	return nil
}

func (m *DepositItem) validateTxHash(formats strfmt.Registry) error {

	if err := validate.Required("tx_hash", "body", m.TxHash); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this deposit item based on context it is used
func (m *DepositItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *DepositItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *DepositItem) UnmarshalBinary(b []byte) error {
	var res DepositItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
