// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetPendingDepositsResponse get pending deposits response
//
// swagger:model getPendingDepositsResponse
type GetPendingDepositsResponse struct {

	// pending deposits
	// Required: true
	PendingDeposits []*PendingDepositItem `json:"pending_deposits"`
}

// Validate validates this get pending deposits response
func (m *GetPendingDepositsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePendingDeposits(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetPendingDepositsResponse) validatePendingDeposits(formats strfmt.Registry) error {

	if err := validate.Required("pending_deposits", "body", m.PendingDeposits); err != nil {
		return err
	}

	for i := 0; i < len(m.PendingDeposits); i++ {
		if swag.IsZero(m.PendingDeposits[i]) { // not required
			continue
		}

		if m.PendingDeposits[i] != nil {
			if err := m.PendingDeposits[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("pending_deposits" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("pending_deposits" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get pending deposits response based on the context it is used
func (m *GetPendingDepositsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePendingDeposits(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetPendingDepositsResponse) contextValidatePendingDeposits(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.PendingDeposits); i++ {

		if m.PendingDeposits[i] != nil {
			if err := m.PendingDeposits[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("pending_deposits" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("pending_deposits" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetPendingDepositsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetPendingDepositsResponse) UnmarshalBinary(b []byte) error {
	var res GetPendingDepositsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
