// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetChainsResponse get chains response
//
// swagger:model getChainsResponse
type GetChainsResponse struct {

	// chains
	// Required: true
	Chains []*ChainItem `json:"chains"`
}

// Validate validates this get chains response
func (m *GetChainsResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChains(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetChainsResponse) validateChains(formats strfmt.Registry) error {

	if err := validate.Required("chains", "body", m.Chains); err != nil {
		return err
	}

	for i := 0; i < len(m.Chains); i++ {
		if swag.IsZero(m.Chains[i]) { // not required
			continue
		}

		if m.Chains[i] != nil {
			if err := m.Chains[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("chains" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("chains" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this get chains response based on the context it is used
func (m *GetChainsResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateChains(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetChainsResponse) contextValidateChains(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Chains); i++ {

		if m.Chains[i] != nil {
			if err := m.Chains[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("chains" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("chains" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *GetChainsResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetChainsResponse) UnmarshalBinary(b []byte) error {
	var res GetChainsResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
