// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// GetWalletAddressResponse get wallet address response
//
// swagger:model getWalletAddressResponse
type GetWalletAddressResponse struct {

	// address
	// Example: 0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b6
	// Required: true
	Address *string `json:"address"`

	// chain id
	// Example: 1
	// Required: true
	ChainID *int64 `json:"chain_id"`

	// chain name
	// Example: Ethereum Mainnet
	// Required: true
	ChainName *string `json:"chain_name"`

	// chain type
	// Example: evm
	// Required: true
	ChainType *string `json:"chain_type"`

	// derivation path
	// Example: m/44'/60'/0'/0/0
	// Required: true
	DerivationPath *string `json:"derivation_path"`
}

// Validate validates this get wallet address response
func (m *GetWalletAddressResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateChainID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateChainName(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateChainType(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDerivationPath(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *GetWalletAddressResponse) validateAddress(formats strfmt.Registry) error {

	if err := validate.Required("address", "body", m.Address); err != nil {
		return err
	}

	return nil
}

func (m *GetWalletAddressResponse) validateChainID(formats strfmt.Registry) error {

	if err := validate.Required("chain_id", "body", m.ChainID); err != nil {
		return err
	}

	return nil
}

func (m *GetWalletAddressResponse) validateChainName(formats strfmt.Registry) error {

	if err := validate.Required("chain_name", "body", m.ChainName); err != nil {
		return err
	}

	return nil
}

func (m *GetWalletAddressResponse) validateChainType(formats strfmt.Registry) error {

	if err := validate.Required("chain_type", "body", m.ChainType); err != nil {
		return err
	}

	return nil
}

func (m *GetWalletAddressResponse) validateDerivationPath(formats strfmt.Registry) error {

	if err := validate.Required("derivation_path", "body", m.DerivationPath); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this get wallet address response based on context it is used
func (m *GetWalletAddressResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *GetWalletAddressResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetWalletAddressResponse) UnmarshalBinary(b []byte) error {
	var res GetWalletAddressResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
