// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PendingDepositItem pending deposit item
//
// swagger:model pendingDepositItem
type PendingDepositItem struct {

	// Total pending deposit amount (as string to avoid precision loss)
	// Example: 0.500000
	// Required: true
	PendingAmount *string `json:"pending_amount"`

	// token symbol
	// Example: ETH
	// Required: true
	TokenSymbol *string `json:"token_symbol"`

	// Number of pending deposit transactions
	// Example: 2
	// Required: true
	TransactionCount *int64 `json:"transaction_count"`
}

// Validate validates this pending deposit item
func (m *PendingDepositItem) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePendingAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTokenSymbol(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTransactionCount(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PendingDepositItem) validatePendingAmount(formats strfmt.Registry) error {

	if err := validate.Required("pending_amount", "body", m.PendingAmount); err != nil {
		return err
	}

	return nil
}

func (m *PendingDepositItem) validateTokenSymbol(formats strfmt.Registry) error {

	if err := validate.Required("token_symbol", "body", m.TokenSymbol); err != nil {
		return err
	}

	return nil
}

func (m *PendingDepositItem) validateTransactionCount(formats strfmt.Registry) error {

	if err := validate.Required("transaction_count", "body", m.TransactionCount); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this pending deposit item based on context it is used
func (m *PendingDepositItem) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PendingDepositItem) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PendingDepositItem) UnmarshalBinary(b []byte) error {
	var res PendingDepositItem
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
