// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostRebalancePayload post rebalance payload
//
// swagger:model postRebalancePayload
type PostRebalancePayload struct {

	// Amount in wei (as string to avoid precision loss)
	// Example: 1000000000000000000
	// Required: true
	Amount *string `json:"amount"`

	// Chain ID
	// Example: 1
	// Required: true
	ChainID *int64 `json:"chain_id"`

	// Source hot wallet address
	// Example: 0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b6
	// Required: true
	FromAddress *string `json:"from_address"`

	// Destination hot wallet address
	// Example: 0x8ba1f109551bD432803012645Hac136c22C177E7
	// Required: true
	ToAddress *string `json:"to_address"`
}

// Validate validates this post rebalance payload
func (m *PostRebalancePayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateChainID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFromAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateToAddress(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostRebalancePayload) validateAmount(formats strfmt.Registry) error {

	if err := validate.Required("amount", "body", m.Amount); err != nil {
		return err
	}

	return nil
}

func (m *PostRebalancePayload) validateChainID(formats strfmt.Registry) error {

	if err := validate.Required("chain_id", "body", m.ChainID); err != nil {
		return err
	}

	return nil
}

func (m *PostRebalancePayload) validateFromAddress(formats strfmt.Registry) error {

	if err := validate.Required("from_address", "body", m.FromAddress); err != nil {
		return err
	}

	return nil
}

func (m *PostRebalancePayload) validateToAddress(formats strfmt.Registry) error {

	if err := validate.Required("to_address", "body", m.ToAddress); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post rebalance payload based on context it is used
func (m *PostRebalancePayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostRebalancePayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostRebalancePayload) UnmarshalBinary(b []byte) error {
	var res PostRebalancePayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
