// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostCreateWalletPayload post create wallet payload
//
// swagger:model postCreateWalletPayload
type PostCreateWalletPayload struct {

	// Chain ID (1 for Ethereum Mainnet, 137 for Polygon, 56 for BSC, etc.)
	// Example: 1
	// Required: true
	ChainID *int64 `json:"chain_id"`
}

// Validate validates this post create wallet payload
func (m *PostCreateWalletPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChainID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostCreateWalletPayload) validateChainID(formats strfmt.Registry) error {

	if err := validate.Required("chain_id", "body", m.ChainID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post create wallet payload based on context it is used
func (m *PostCreateWalletPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostCreateWalletPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostCreateWalletPayload) UnmarshalBinary(b []byte) error {
	var res PostCreateWalletPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
