// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostCreateHotWalletPayload post create hot wallet payload
//
// swagger:model postCreateHotWalletPayload
type PostCreateHotWalletPayload struct {

	// Chain ID (1 for Ethereum Mainnet, 137 for Polygon, 56 for BSC, etc.)
	// Example: 1
	// Required: true
	ChainID *int64 `json:"chain_id"`

	// Device name for the hot wallet
	// Example: hot-wallet-1
	// Required: true
	DeviceName *string `json:"device_name"`
}

// Validate validates this post create hot wallet payload
func (m *PostCreateHotWalletPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChainID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateDeviceName(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostCreateHotWalletPayload) validateChainID(formats strfmt.Registry) error {

	if err := validate.Required("chain_id", "body", m.ChainID); err != nil {
		return err
	}

	return nil
}

func (m *PostCreateHotWalletPayload) validateDeviceName(formats strfmt.Registry) error {

	if err := validate.Required("device_name", "body", m.DeviceName); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post create hot wallet payload based on context it is used
func (m *PostCreateHotWalletPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostCreateHotWalletPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostCreateHotWalletPayload) UnmarshalBinary(b []byte) error {
	var res PostCreateHotWalletPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
