// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostSignTransactionPayload post sign transaction payload
//
// swagger:model postSignTransactionPayload
type PostSignTransactionPayload struct {

	// Chain ID
	// Example: 1
	// Required: true
	ChainID *int64 `json:"chain_id"`

	// Transaction data (for contract calls, optional)
	// Format: byte
	Data strfmt.Base64 `json:"data,omitempty"`

	// Address to sign from
	// Example: 0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b6
	// Required: true
	FromAddress *string `json:"from_address"`

	// Gas limit
	// Example: 21000
	// Required: true
	GasLimit *int64 `json:"gas_limit"`

	// Max fee per gas (EIP-1559, in wei, as string)
	// Example: 20000000000
	// Required: true
	MaxFeePerGas *string `json:"max_fee_per_gas"`

	// Max priority fee per gas (EIP-1559, in wei, as string)
	// Example: 1000000000
	// Required: true
	MaxPriorityFeePerGas *string `json:"max_priority_fee_per_gas"`

	// Transaction nonce
	// Example: 0
	// Required: true
	Nonce *int64 `json:"nonce"`

	// Recipient address
	// Example: 0x8ba1f109551bD432803012645Hac136c22C177E7
	// Required: true
	To *string `json:"to"`

	// Amount in wei (as string to avoid precision loss)
	// Example: 1000000000000000000
	// Required: true
	Value *string `json:"value"`
}

// Validate validates this post sign transaction payload
func (m *PostSignTransactionPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateChainID(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFromAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateGasLimit(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMaxFeePerGas(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateMaxPriorityFeePerGas(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateNonce(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTo(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostSignTransactionPayload) validateChainID(formats strfmt.Registry) error {

	if err := validate.Required("chain_id", "body", m.ChainID); err != nil {
		return err
	}

	return nil
}

func (m *PostSignTransactionPayload) validateFromAddress(formats strfmt.Registry) error {

	if err := validate.Required("from_address", "body", m.FromAddress); err != nil {
		return err
	}

	return nil
}

func (m *PostSignTransactionPayload) validateGasLimit(formats strfmt.Registry) error {

	if err := validate.Required("gas_limit", "body", m.GasLimit); err != nil {
		return err
	}

	return nil
}

func (m *PostSignTransactionPayload) validateMaxFeePerGas(formats strfmt.Registry) error {

	if err := validate.Required("max_fee_per_gas", "body", m.MaxFeePerGas); err != nil {
		return err
	}

	return nil
}

func (m *PostSignTransactionPayload) validateMaxPriorityFeePerGas(formats strfmt.Registry) error {

	if err := validate.Required("max_priority_fee_per_gas", "body", m.MaxPriorityFeePerGas); err != nil {
		return err
	}

	return nil
}

func (m *PostSignTransactionPayload) validateNonce(formats strfmt.Registry) error {

	if err := validate.Required("nonce", "body", m.Nonce); err != nil {
		return err
	}

	return nil
}

func (m *PostSignTransactionPayload) validateTo(formats strfmt.Registry) error {

	if err := validate.Required("to", "body", m.To); err != nil {
		return err
	}

	return nil
}

func (m *PostSignTransactionPayload) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post sign transaction payload based on context it is used
func (m *PostSignTransactionPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostSignTransactionPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostSignTransactionPayload) UnmarshalBinary(b []byte) error {
	var res PostSignTransactionPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
