// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostCollectPayload post collect payload
//
// swagger:model postCollectPayload
type PostCollectPayload struct {

	// Chain ID (optional, will use wallet's chain_id if not provided)
	// Example: 1
	ChainID int64 `json:"chain_id,omitempty"`

	// Wallet ID to collect from
	// Example: 550e8400-e29b-41d4-a716-446655440000
	// Required: true
	// Format: uuid
	WalletID *strfmt.UUID `json:"wallet_id"`
}

// Validate validates this post collect payload
func (m *PostCollectPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateWalletID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostCollectPayload) validateWalletID(formats strfmt.Registry) error {

	if err := validate.Required("wallet_id", "body", m.WalletID); err != nil {
		return err
	}

	if err := validate.FormatOf("wallet_id", "body", "uuid", m.WalletID.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post collect payload based on context it is used
func (m *PostCollectPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostCollectPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostCollectPayload) UnmarshalBinary(b []byte) error {
	var res PostCollectPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
