// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostWithdrawPayload post withdraw payload
//
// swagger:model postWithdrawPayload
type PostWithdrawPayload struct {

	// Amount to withdraw (human readable)
	// Example: 1.5
	// Required: true
	Amount *string `json:"amount"`

	// Destination address
	// Example: 0x742d35Cc6634C0532925a3b8D4C9db96C4b4d8b6
	// Required: true
	ToAddress *string `json:"to_address"`

	// Token ID to withdraw
	// Example: 1
	// Required: true
	TokenID *int64 `json:"token_id"`
}

// Validate validates this post withdraw payload
func (m *PostWithdrawPayload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAmount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateToAddress(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTokenID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PostWithdrawPayload) validateAmount(formats strfmt.Registry) error {

	if err := validate.Required("amount", "body", m.Amount); err != nil {
		return err
	}

	return nil
}

func (m *PostWithdrawPayload) validateToAddress(formats strfmt.Registry) error {

	if err := validate.Required("to_address", "body", m.ToAddress); err != nil {
		return err
	}

	return nil
}

func (m *PostWithdrawPayload) validateTokenID(formats strfmt.Registry) error {

	if err := validate.Required("token_id", "body", m.TokenID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post withdraw payload based on context it is used
func (m *PostWithdrawPayload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PostWithdrawPayload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PostWithdrawPayload) UnmarshalBinary(b []byte) error {
	var res PostWithdrawPayload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
