// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// SignTransactionResponse sign transaction response
//
// swagger:model signTransactionResponse
type SignTransactionResponse struct {

	// RLP-encoded signed transaction
	// Required: true
	// Format: byte
	RawTransaction *strfmt.Base64 `json:"raw_transaction"`

	// Transaction hash (hex string with 0x prefix)
	// Example: 0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef
	// Required: true
	TxHash *string `json:"tx_hash"`
}

// Validate validates this sign transaction response
func (m *SignTransactionResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRawTransaction(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTxHash(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SignTransactionResponse) validateRawTransaction(formats strfmt.Registry) error {

	if err := validate.Required("raw_transaction", "body", m.RawTransaction); err != nil {
		return err
	}

	return nil
}

func (m *SignTransactionResponse) validateTxHash(formats strfmt.Registry) error {

	if err := validate.Required("tx_hash", "body", m.TxHash); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this sign transaction response based on context it is used
func (m *SignTransactionResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SignTransactionResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SignTransactionResponse) UnmarshalBinary(b []byte) error {
	var res SignTransactionResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
