// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// TotalBalanceResponse total balance response
//
// swagger:model totalBalanceResponse
type TotalBalanceResponse struct {

	// Number of token types with balance
	// Example: 3
	// Required: true
	TokenCount *int64 `json:"token_count"`

	// Total finalized balance (as string to avoid precision loss)
	// Example: 100.500000
	// Required: true
	TotalAmount *string `json:"total_amount"`
}

// Validate validates this total balance response
func (m *TotalBalanceResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTokenCount(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateTotalAmount(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *TotalBalanceResponse) validateTokenCount(formats strfmt.Registry) error {

	if err := validate.Required("token_count", "body", m.TokenCount); err != nil {
		return err
	}

	return nil
}

func (m *TotalBalanceResponse) validateTotalAmount(formats strfmt.Registry) error {

	if err := validate.Required("total_amount", "body", m.TotalAmount); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this total balance response based on context it is used
func (m *TotalBalanceResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *TotalBalanceResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *TotalBalanceResponse) UnmarshalBinary(b []byte) error {
	var res TotalBalanceResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
