// Code generated by go-swagger; DO NOT EDIT.

package types

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// WithdrawResponse withdraw response
//
// swagger:model withdrawResponse
type WithdrawResponse struct {

	// withdraw
	// Required: true
	Withdraw *WithdrawItem `json:"withdraw"`
}

// Validate validates this withdraw response
func (m *WithdrawResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateWithdraw(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WithdrawResponse) validateWithdraw(formats strfmt.Registry) error {

	if err := validate.Required("withdraw", "body", m.Withdraw); err != nil {
		return err
	}

	if m.Withdraw != nil {
		if err := m.Withdraw.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("withdraw")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("withdraw")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this withdraw response based on the context it is used
func (m *WithdrawResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateWithdraw(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *WithdrawResponse) contextValidateWithdraw(ctx context.Context, formats strfmt.Registry) error {

	if m.Withdraw != nil {
		if err := m.Withdraw.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("withdraw")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("withdraw")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *WithdrawResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *WithdrawResponse) UnmarshalBinary(b []byte) error {
	var res WithdrawResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
