swagger: "2.0"
info:
  title: github/chapool/go-wallet
  version: 0.1.0
paths:
  /api/v1/wallet/create:
    post:
      summary: Create wallet
      operationId: PostCreateWalletRoute
      description: |-
        Create a wallet for the authenticated user on the specified chain.
        If the user already has a wallet on this chain, returns the existing wallet.
      tags:
        - wallet
      security:
        - Bearer: []
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: "../definitions/wallet.yml#/definitions/PostCreateWalletPayload"
      responses:
        "200":
          description: Wallet created or retrieved successfully
          schema:
            $ref: "../definitions/wallet.yml#/definitions/CreateWalletResponse"
        "400":
          description: PublicHTTPValidationError
          schema:
            $ref: "../definitions/errors.yml#/definitions/PublicHTTPValidationError"
        "401":
          description: PublicHTTPError
          schema:
            $ref: "../definitions/errors.yml#/definitions/PublicHTTPError"
        "500":
          description: PublicHTTPError
          schema:
            $ref: "../definitions/errors.yml#/definitions/PublicHTTPError"
  
  /api/v1/wallet/address:
    get:
      summary: Get wallet address
      operationId: GetWalletAddressRoute
      description: |-
        Get the wallet address for the authenticated user on the specified chain.
      tags:
        - wallet
      security:
        - Bearer: []
      produces:
        - application/json
      parameters:
        - name: chain_id
          in: query
          type: integer
          description: Chain ID (1 for Ethereum Mainnet, 137 for Polygon, 56 for BSC, etc.)
          required: true
      responses:
        "200":
          description: Wallet address retrieved successfully
          schema:
            $ref: "../definitions/wallet.yml#/definitions/GetWalletAddressResponse"
        "400":
          description: PublicHTTPValidationError
          schema:
            $ref: "../definitions/errors.yml#/definitions/PublicHTTPValidationError"
        "401":
          description: PublicHTTPError
          schema:
            $ref: "../definitions/errors.yml#/definitions/PublicHTTPError"
        "404":
          description: PublicHTTPError
          schema:
            $ref: "../definitions/errors.yml#/definitions/PublicHTTPError"
        "500":
          description: PublicHTTPError
          schema:
            $ref: "../definitions/errors.yml#/definitions/PublicHTTPError"
  
  /api/v1/wallet/list:
    get:
      summary: List all wallets
      operationId: GetWalletListRoute
      description: |-
        List all wallets for the authenticated user across all chains.
      tags:
        - wallet
      security:
        - Bearer: []
      produces:
        - application/json
      responses:
        "200":
          description: Wallet list retrieved successfully
          schema:
            $ref: "../definitions/wallet.yml#/definitions/GetWalletListResponse"
        "401":
          description: PublicHTTPError
          schema:
            $ref: "../definitions/errors.yml#/definitions/PublicHTTPError"
        "500":
          description: PublicHTTPError
          schema:
            $ref: "../definitions/errors.yml#/definitions/PublicHTTPError"
  
  /api/v1/wallet/sign-transaction:
    post:
      summary: Sign transaction
      operationId: PostSignTransactionRoute
      description: |-
        Sign an EVM transaction (EIP-1559). This is a test endpoint for transaction signing.
      tags:
        - wallet
      security:
        - Bearer: []
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: body
          in: body
          required: true
          schema:
            $ref: "../definitions/wallet.yml#/definitions/PostSignTransactionPayload"
      responses:
        "200":
          description: Transaction signed successfully
          schema:
            $ref: "../definitions/wallet.yml#/definitions/SignTransactionResponse"
        "400":
          description: PublicHTTPValidationError
          schema:
            $ref: "../definitions/errors.yml#/definitions/PublicHTTPValidationError"
        "401":
          description: PublicHTTPError
          schema:
            $ref: "../definitions/errors.yml#/definitions/PublicHTTPError"
        "500":
          description: PublicHTTPError
          schema:
            $ref: "../definitions/errors.yml#/definitions/PublicHTTPError"
  
  /api/v1/wallet/chains:
    get:
      summary: Get supported chains
      operationId: GetChainsRoute
      description: |-
        Get list of supported EVM chains.
      tags:
        - wallet
      security:
        - Bearer: []
      produces:
        - application/json
      responses:
        "200":
          description: Chains retrieved successfully
          schema:
            $ref: "../definitions/wallet.yml#/definitions/GetChainsResponse"
        "401":
          description: PublicHTTPError
          schema:
            $ref: "../definitions/errors.yml#/definitions/PublicHTTPError"
        "500":
          description: PublicHTTPError
          schema:
            $ref: "../definitions/errors.yml#/definitions/PublicHTTPError"
  
  /api/v1/wallet/deposits:
    get:
      summary: Get deposit records
      operationId: GetDepositsRoute
      description: |-
        Get deposit records for the authenticated user.
        Supports filtering by chain_id and status.
      tags:
        - wallet
      security:
        - Bearer: []
      produces:
        - application/json
      parameters:
        - name: chain_id
          type: integer
          in: query
          required: false
          description: Chain ID (1 for Ethereum Mainnet, 137 for Polygon, 56 for BSC, etc.)
        - name: status
          type: string
          in: query
          required: false
          description: Filter by transaction status
          enum: [confirmed, safe, finalized, failed]
        - $ref: "../definitions/common.yml#/parameters/offsetParam"
        - $ref: "../definitions/common.yml#/parameters/limitParam"
      responses:
        "200":
          description: List of deposit records
          schema:
            $ref: "../definitions/wallet.yml#/definitions/GetDepositsResponse"
        "400":
          description: PublicHTTPValidationError
          schema:
            $ref: "../definitions/errors.yml#/definitions/PublicHTTPValidationError"
        "401":
          description: PublicHTTPError
          schema:
            $ref: "../definitions/errors.yml#/definitions/PublicHTTPError"
        "500":
          description: PublicHTTPError
          schema:
            $ref: "../definitions/errors.yml#/definitions/PublicHTTPError"
  
  /api/v1/wallet/deposits/pending:
    get:
      summary: Get pending deposit balances
      operationId: GetPendingDepositsRoute
      description: |-
        Get pending deposit balances grouped by token symbol for the authenticated user.
        Returns deposits with status 'confirmed' or 'safe' (not yet finalized).
      tags:
        - wallet
      security:
        - Bearer: []
      produces:
        - application/json
      parameters:
        - name: chain_id
          type: integer
          in: query
          required: false
          description: Chain ID (1 for Ethereum Mainnet, 137 for Polygon, 56 for BSC, etc.)
      responses:
        "200":
          description: Pending deposit balances retrieved successfully
          schema:
            $ref: "../definitions/wallet.yml#/definitions/GetPendingDepositsResponse"
        "401":
          description: PublicHTTPError
          schema:
            $ref: "../definitions/errors.yml#/definitions/PublicHTTPError"
        "500":
          description: PublicHTTPError
          schema:
            $ref: "../definitions/errors.yml#/definitions/PublicHTTPError"

