// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Chain is an object representing the database table.
type Chain struct {
	ID                 int         `boil:"id" json:"id" toml:"id" yaml:"id"`
	ChainID            int         `boil:"chain_id" json:"chain_id" toml:"chain_id" yaml:"chain_id"`
	ChainName          string      `boil:"chain_name" json:"chain_name" toml:"chain_name" yaml:"chain_name"`
	ChainType          string      `boil:"chain_type" json:"chain_type" toml:"chain_type" yaml:"chain_type"`
	RPCURL             string      `boil:"rpc_url" json:"rpc_url" toml:"rpc_url" yaml:"rpc_url"`
	ExplorerURL        null.String `boil:"explorer_url" json:"explorer_url,omitempty" toml:"explorer_url" yaml:"explorer_url,omitempty"`
	NativeTokenSymbol  string      `boil:"native_token_symbol" json:"native_token_symbol" toml:"native_token_symbol" yaml:"native_token_symbol"`
	BlockTimeSeconds   null.Int    `boil:"block_time_seconds" json:"block_time_seconds,omitempty" toml:"block_time_seconds" yaml:"block_time_seconds,omitempty"`
	ConfirmationBlocks null.Int    `boil:"confirmation_blocks" json:"confirmation_blocks,omitempty" toml:"confirmation_blocks" yaml:"confirmation_blocks,omitempty"`
	FinalizedBlocks    null.Int    `boil:"finalized_blocks" json:"finalized_blocks,omitempty" toml:"finalized_blocks" yaml:"finalized_blocks,omitempty"`
	IsActive           bool        `boil:"is_active" json:"is_active" toml:"is_active" yaml:"is_active"`
	CreatedAt          time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt          time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *chainR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L chainL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var ChainColumns = struct {
	ID                 string
	ChainID            string
	ChainName          string
	ChainType          string
	RPCURL             string
	ExplorerURL        string
	NativeTokenSymbol  string
	BlockTimeSeconds   string
	ConfirmationBlocks string
	FinalizedBlocks    string
	IsActive           string
	CreatedAt          string
	UpdatedAt          string
}{
	ID:                 "id",
	ChainID:            "chain_id",
	ChainName:          "chain_name",
	ChainType:          "chain_type",
	RPCURL:             "rpc_url",
	ExplorerURL:        "explorer_url",
	NativeTokenSymbol:  "native_token_symbol",
	BlockTimeSeconds:   "block_time_seconds",
	ConfirmationBlocks: "confirmation_blocks",
	FinalizedBlocks:    "finalized_blocks",
	IsActive:           "is_active",
	CreatedAt:          "created_at",
	UpdatedAt:          "updated_at",
}

var ChainTableColumns = struct {
	ID                 string
	ChainID            string
	ChainName          string
	ChainType          string
	RPCURL             string
	ExplorerURL        string
	NativeTokenSymbol  string
	BlockTimeSeconds   string
	ConfirmationBlocks string
	FinalizedBlocks    string
	IsActive           string
	CreatedAt          string
	UpdatedAt          string
}{
	ID:                 "chains.id",
	ChainID:            "chains.chain_id",
	ChainName:          "chains.chain_name",
	ChainType:          "chains.chain_type",
	RPCURL:             "chains.rpc_url",
	ExplorerURL:        "chains.explorer_url",
	NativeTokenSymbol:  "chains.native_token_symbol",
	BlockTimeSeconds:   "chains.block_time_seconds",
	ConfirmationBlocks: "chains.confirmation_blocks",
	FinalizedBlocks:    "chains.finalized_blocks",
	IsActive:           "chains.is_active",
	CreatedAt:          "chains.created_at",
	UpdatedAt:          "chains.updated_at",
}

// Generated where

type whereHelpernull_Int struct{ field string }

func (w whereHelpernull_Int) EQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Int) NEQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Int) LT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Int) LTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Int) GT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Int) GTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Int) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Int) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Int) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Int) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelperbool struct{ field string }

func (w whereHelperbool) EQ(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperbool) NEQ(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperbool) LT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperbool) LTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperbool) GT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperbool) GTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }

var ChainWhere = struct {
	ID                 whereHelperint
	ChainID            whereHelperint
	ChainName          whereHelperstring
	ChainType          whereHelperstring
	RPCURL             whereHelperstring
	ExplorerURL        whereHelpernull_String
	NativeTokenSymbol  whereHelperstring
	BlockTimeSeconds   whereHelpernull_Int
	ConfirmationBlocks whereHelpernull_Int
	FinalizedBlocks    whereHelpernull_Int
	IsActive           whereHelperbool
	CreatedAt          whereHelpertime_Time
	UpdatedAt          whereHelpertime_Time
}{
	ID:                 whereHelperint{field: "\"chains\".\"id\""},
	ChainID:            whereHelperint{field: "\"chains\".\"chain_id\""},
	ChainName:          whereHelperstring{field: "\"chains\".\"chain_name\""},
	ChainType:          whereHelperstring{field: "\"chains\".\"chain_type\""},
	RPCURL:             whereHelperstring{field: "\"chains\".\"rpc_url\""},
	ExplorerURL:        whereHelpernull_String{field: "\"chains\".\"explorer_url\""},
	NativeTokenSymbol:  whereHelperstring{field: "\"chains\".\"native_token_symbol\""},
	BlockTimeSeconds:   whereHelpernull_Int{field: "\"chains\".\"block_time_seconds\""},
	ConfirmationBlocks: whereHelpernull_Int{field: "\"chains\".\"confirmation_blocks\""},
	FinalizedBlocks:    whereHelpernull_Int{field: "\"chains\".\"finalized_blocks\""},
	IsActive:           whereHelperbool{field: "\"chains\".\"is_active\""},
	CreatedAt:          whereHelpertime_Time{field: "\"chains\".\"created_at\""},
	UpdatedAt:          whereHelpertime_Time{field: "\"chains\".\"updated_at\""},
}

// ChainRels is where relationship names are stored.
var ChainRels = struct {
}{}

// chainR is where relationships are stored.
type chainR struct {
}

// NewStruct creates a new relationship struct
func (*chainR) NewStruct() *chainR {
	return &chainR{}
}

// chainL is where Load methods for each relationship are stored.
type chainL struct{}

var (
	chainAllColumns            = []string{"id", "chain_id", "chain_name", "chain_type", "rpc_url", "explorer_url", "native_token_symbol", "block_time_seconds", "confirmation_blocks", "finalized_blocks", "is_active", "created_at", "updated_at"}
	chainColumnsWithoutDefault = []string{"chain_id", "chain_name", "chain_type", "rpc_url", "native_token_symbol", "is_active"}
	chainColumnsWithDefault    = []string{"id", "explorer_url", "block_time_seconds", "confirmation_blocks", "finalized_blocks", "created_at", "updated_at"}
	chainPrimaryKeyColumns     = []string{"id"}
	chainGeneratedColumns      = []string{}
)

type (
	// ChainSlice is an alias for a slice of pointers to Chain.
	// This should almost always be used instead of []Chain.
	ChainSlice []*Chain

	chainQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	chainType                 = reflect.TypeOf(&Chain{})
	chainMapping              = queries.MakeStructMapping(chainType)
	chainPrimaryKeyMapping, _ = queries.BindMapping(chainType, chainMapping, chainPrimaryKeyColumns)
	chainInsertCacheMut       sync.RWMutex
	chainInsertCache          = make(map[string]insertCache)
	chainUpdateCacheMut       sync.RWMutex
	chainUpdateCache          = make(map[string]updateCache)
	chainUpsertCacheMut       sync.RWMutex
	chainUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single chain record from the query.
func (q chainQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Chain, error) {
	o := &Chain{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for chains")
	}

	return o, nil
}

// All returns all Chain records from the query.
func (q chainQuery) All(ctx context.Context, exec boil.ContextExecutor) (ChainSlice, error) {
	var o []*Chain

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Chain slice")
	}

	return o, nil
}

// Count returns the count of all Chain records in the query.
func (q chainQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count chains rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q chainQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if chains exists")
	}

	return count > 0, nil
}

// Chains retrieves all the records using an executor.
func Chains(mods ...qm.QueryMod) chainQuery {
	mods = append(mods, qm.From("\"chains\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"chains\".*"})
	}

	return chainQuery{q}
}

// FindChain retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindChain(ctx context.Context, exec boil.ContextExecutor, iD int, selectCols ...string) (*Chain, error) {
	chainObj := &Chain{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"chains\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, chainObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from chains")
	}

	return chainObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Chain) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no chains provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(chainColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	chainInsertCacheMut.RLock()
	cache, cached := chainInsertCache[key]
	chainInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			chainAllColumns,
			chainColumnsWithDefault,
			chainColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(chainType, chainMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(chainType, chainMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"chains\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"chains\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into chains")
	}

	if !cached {
		chainInsertCacheMut.Lock()
		chainInsertCache[key] = cache
		chainInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the Chain.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Chain) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	chainUpdateCacheMut.RLock()
	cache, cached := chainUpdateCache[key]
	chainUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			chainAllColumns,
			chainPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update chains, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"chains\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, chainPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(chainType, chainMapping, append(wl, chainPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update chains row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for chains")
	}

	if !cached {
		chainUpdateCacheMut.Lock()
		chainUpdateCache[key] = cache
		chainUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q chainQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for chains")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for chains")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o ChainSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), chainPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"chains\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, chainPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in chain slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all chain")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Chain) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no chains provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(chainColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	chainUpsertCacheMut.RLock()
	cache, cached := chainUpsertCache[key]
	chainUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			chainAllColumns,
			chainColumnsWithDefault,
			chainColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			chainAllColumns,
			chainPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert chains, could not build update column list")
		}

		ret := strmangle.SetComplement(chainAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(chainPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert chains, could not build conflict column list")
			}

			conflict = make([]string, len(chainPrimaryKeyColumns))
			copy(conflict, chainPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"chains\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(chainType, chainMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(chainType, chainMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert chains")
	}

	if !cached {
		chainUpsertCacheMut.Lock()
		chainUpsertCache[key] = cache
		chainUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single Chain record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Chain) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Chain provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), chainPrimaryKeyMapping)
	sql := "DELETE FROM \"chains\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from chains")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for chains")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q chainQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no chainQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from chains")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for chains")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o ChainSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), chainPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"chains\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, chainPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from chain slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for chains")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Chain) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindChain(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *ChainSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := ChainSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), chainPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"chains\".* FROM \"chains\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, chainPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in ChainSlice")
	}

	*o = slice

	return nil
}

// ChainExists checks if the Chain row exists.
func ChainExists(ctx context.Context, exec boil.ContextExecutor, iD int) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"chains\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if chains exists")
	}

	return exists, nil
}

// Exists checks if the Chain row exists.
func (o *Chain) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return ChainExists(ctx, exec, o.ID)
}
