// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testCredits(t *testing.T) {
	t.Parallel()

	query := Credits()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testCreditsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Credit{}
	if err = randomize.Struct(seed, o, creditDBTypes, true, creditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Credit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Credits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCreditsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Credit{}
	if err = randomize.Struct(seed, o, creditDBTypes, true, creditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Credit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Credits().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Credits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCreditsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Credit{}
	if err = randomize.Struct(seed, o, creditDBTypes, true, creditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Credit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CreditSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Credits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testCreditsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Credit{}
	if err = randomize.Struct(seed, o, creditDBTypes, true, creditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Credit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := CreditExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Credit exists: %s", err)
	}
	if !e {
		t.Errorf("Expected CreditExists to return true, but got false.")
	}
}

func testCreditsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Credit{}
	if err = randomize.Struct(seed, o, creditDBTypes, true, creditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Credit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	creditFound, err := FindCredit(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if creditFound == nil {
		t.Error("want a record, got nil")
	}
}

func testCreditsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Credit{}
	if err = randomize.Struct(seed, o, creditDBTypes, true, creditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Credit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Credits().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testCreditsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Credit{}
	if err = randomize.Struct(seed, o, creditDBTypes, true, creditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Credit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Credits().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testCreditsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	creditOne := &Credit{}
	creditTwo := &Credit{}
	if err = randomize.Struct(seed, creditOne, creditDBTypes, false, creditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Credit struct: %s", err)
	}
	if err = randomize.Struct(seed, creditTwo, creditDBTypes, false, creditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Credit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = creditOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = creditTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Credits().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testCreditsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	creditOne := &Credit{}
	creditTwo := &Credit{}
	if err = randomize.Struct(seed, creditOne, creditDBTypes, false, creditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Credit struct: %s", err)
	}
	if err = randomize.Struct(seed, creditTwo, creditDBTypes, false, creditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Credit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = creditOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = creditTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Credits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testCreditsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Credit{}
	if err = randomize.Struct(seed, o, creditDBTypes, true, creditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Credit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Credits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCreditsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Credit{}
	if err = randomize.Struct(seed, o, creditDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Credit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(creditPrimaryKeyColumns, creditColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := Credits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testCreditToOneTokenUsingToken(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Credit
	var foreign Token

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, creditDBTypes, false, creditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Credit struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, tokenDBTypes, false, tokenColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Token struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.TokenID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Token().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := CreditSlice{&local}
	if err = local.L.LoadToken(ctx, tx, false, (*[]*Credit)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Token == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Token = nil
	if err = local.L.LoadToken(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Token == nil {
		t.Error("struct should have been eager loaded")
	}

}

func testCreditToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Credit
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, creditDBTypes, false, creditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Credit struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := CreditSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*Credit)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

}

func testCreditToOneSetOpTokenUsingToken(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Credit
	var b, c Token

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, creditDBTypes, false, strmangle.SetComplement(creditPrimaryKeyColumns, creditColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, tokenDBTypes, false, strmangle.SetComplement(tokenPrimaryKeyColumns, tokenColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, tokenDBTypes, false, strmangle.SetComplement(tokenPrimaryKeyColumns, tokenColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Token{&b, &c} {
		err = a.SetToken(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Token != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Credits[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.TokenID != x.ID {
			t.Error("foreign key was wrong value", a.TokenID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.TokenID))
		reflect.Indirect(reflect.ValueOf(&a.TokenID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.TokenID != x.ID {
			t.Error("foreign key was wrong value", a.TokenID, x.ID)
		}
	}
}
func testCreditToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Credit
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, creditDBTypes, false, strmangle.SetComplement(creditPrimaryKeyColumns, creditColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Credits[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testCreditsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Credit{}
	if err = randomize.Struct(seed, o, creditDBTypes, true, creditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Credit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testCreditsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Credit{}
	if err = randomize.Struct(seed, o, creditDBTypes, true, creditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Credit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := CreditSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testCreditsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Credit{}
	if err = randomize.Struct(seed, o, creditDBTypes, true, creditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Credit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Credits().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	creditDBTypes = map[string]string{`ID`: `uuid`, `UserID`: `uuid`, `Address`: `character varying`, `TokenID`: `integer`, `TokenSymbol`: `character varying`, `Amount`: `text`, `CreditType`: `enum.credit_type('deposit','withdraw','collect','rebalance','freeze','unfreeze')`, `BusinessType`: `enum.business_type('blockchain','internal_transfer','admin_adjust')`, `ReferenceID`: `text`, `ReferenceType`: `enum.reference_type('blockchain_tx','withdraw','collect','rebalance')`, `ChainID`: `integer`, `ChainType`: `character varying`, `Status`: `enum.credit_status('pending','confirmed','finalized','failed','frozen')`, `BlockNumber`: `bigint`, `TXHash`: `character varying`, `EventIndex`: `integer`, `Metadata`: `jsonb`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`}
	_             = bytes.MinRead
)

func testCreditsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(creditPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(creditAllColumns) == len(creditPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Credit{}
	if err = randomize.Struct(seed, o, creditDBTypes, true, creditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Credit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Credits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, creditDBTypes, true, creditPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Credit struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testCreditsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(creditAllColumns) == len(creditPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Credit{}
	if err = randomize.Struct(seed, o, creditDBTypes, true, creditColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Credit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Credits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, creditDBTypes, true, creditPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Credit struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(creditAllColumns, creditPrimaryKeyColumns) {
		fields = creditAllColumns
	} else {
		fields = strmangle.SetComplement(
			creditAllColumns,
			creditPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := CreditSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testCreditsUpsert(t *testing.T) {
	t.Parallel()

	if len(creditAllColumns) == len(creditPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Credit{}
	if err = randomize.Struct(seed, &o, creditDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Credit struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Credit: %s", err)
	}

	count, err := Credits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, creditDBTypes, false, creditPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Credit struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Credit: %s", err)
	}

	count, err = Credits().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
