// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Keystore is an object representing the database table.
type Keystore struct {
	ID                  string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	KeystoreData        types.JSON  `boil:"keystore_data" json:"keystore_data" toml:"keystore_data" yaml:"keystore_data"`
	Version             int         `boil:"version" json:"version" toml:"version" yaml:"version"`
	Cipher              string      `boil:"cipher" json:"cipher" toml:"cipher" yaml:"cipher"`
	KDF                 string      `boil:"kdf" json:"kdf" toml:"kdf" yaml:"kdf"`
	DeviceName          null.String `boil:"device_name" json:"device_name,omitempty" toml:"device_name" yaml:"device_name,omitempty"`
	CreatedAt           time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt           time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	VerificationAddress null.String `boil:"verification_address" json:"verification_address,omitempty" toml:"verification_address" yaml:"verification_address,omitempty"`

	R *keystoreR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L keystoreL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var KeystoreColumns = struct {
	ID                  string
	KeystoreData        string
	Version             string
	Cipher              string
	KDF                 string
	DeviceName          string
	CreatedAt           string
	UpdatedAt           string
	VerificationAddress string
}{
	ID:                  "id",
	KeystoreData:        "keystore_data",
	Version:             "version",
	Cipher:              "cipher",
	KDF:                 "kdf",
	DeviceName:          "device_name",
	CreatedAt:           "created_at",
	UpdatedAt:           "updated_at",
	VerificationAddress: "verification_address",
}

var KeystoreTableColumns = struct {
	ID                  string
	KeystoreData        string
	Version             string
	Cipher              string
	KDF                 string
	DeviceName          string
	CreatedAt           string
	UpdatedAt           string
	VerificationAddress string
}{
	ID:                  "keystore.id",
	KeystoreData:        "keystore.keystore_data",
	Version:             "keystore.version",
	Cipher:              "keystore.cipher",
	KDF:                 "keystore.kdf",
	DeviceName:          "keystore.device_name",
	CreatedAt:           "keystore.created_at",
	UpdatedAt:           "keystore.updated_at",
	VerificationAddress: "keystore.verification_address",
}

// Generated where

type whereHelpertypes_JSON struct{ field string }

func (w whereHelpertypes_JSON) EQ(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertypes_JSON) NEQ(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertypes_JSON) LT(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_JSON) LTE(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_JSON) GT(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_JSON) GTE(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var KeystoreWhere = struct {
	ID                  whereHelperstring
	KeystoreData        whereHelpertypes_JSON
	Version             whereHelperint
	Cipher              whereHelperstring
	KDF                 whereHelperstring
	DeviceName          whereHelpernull_String
	CreatedAt           whereHelpertime_Time
	UpdatedAt           whereHelpertime_Time
	VerificationAddress whereHelpernull_String
}{
	ID:                  whereHelperstring{field: "\"keystore\".\"id\""},
	KeystoreData:        whereHelpertypes_JSON{field: "\"keystore\".\"keystore_data\""},
	Version:             whereHelperint{field: "\"keystore\".\"version\""},
	Cipher:              whereHelperstring{field: "\"keystore\".\"cipher\""},
	KDF:                 whereHelperstring{field: "\"keystore\".\"kdf\""},
	DeviceName:          whereHelpernull_String{field: "\"keystore\".\"device_name\""},
	CreatedAt:           whereHelpertime_Time{field: "\"keystore\".\"created_at\""},
	UpdatedAt:           whereHelpertime_Time{field: "\"keystore\".\"updated_at\""},
	VerificationAddress: whereHelpernull_String{field: "\"keystore\".\"verification_address\""},
}

// KeystoreRels is where relationship names are stored.
var KeystoreRels = struct {
}{}

// keystoreR is where relationships are stored.
type keystoreR struct {
}

// NewStruct creates a new relationship struct
func (*keystoreR) NewStruct() *keystoreR {
	return &keystoreR{}
}

// keystoreL is where Load methods for each relationship are stored.
type keystoreL struct{}

var (
	keystoreAllColumns            = []string{"id", "keystore_data", "version", "cipher", "kdf", "device_name", "created_at", "updated_at", "verification_address"}
	keystoreColumnsWithoutDefault = []string{"keystore_data", "version", "cipher", "kdf"}
	keystoreColumnsWithDefault    = []string{"id", "device_name", "created_at", "updated_at", "verification_address"}
	keystorePrimaryKeyColumns     = []string{"id"}
	keystoreGeneratedColumns      = []string{}
)

type (
	// KeystoreSlice is an alias for a slice of pointers to Keystore.
	// This should almost always be used instead of []Keystore.
	KeystoreSlice []*Keystore

	keystoreQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	keystoreType                 = reflect.TypeOf(&Keystore{})
	keystoreMapping              = queries.MakeStructMapping(keystoreType)
	keystorePrimaryKeyMapping, _ = queries.BindMapping(keystoreType, keystoreMapping, keystorePrimaryKeyColumns)
	keystoreInsertCacheMut       sync.RWMutex
	keystoreInsertCache          = make(map[string]insertCache)
	keystoreUpdateCacheMut       sync.RWMutex
	keystoreUpdateCache          = make(map[string]updateCache)
	keystoreUpsertCacheMut       sync.RWMutex
	keystoreUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single keystore record from the query.
func (q keystoreQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Keystore, error) {
	o := &Keystore{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for keystore")
	}

	return o, nil
}

// All returns all Keystore records from the query.
func (q keystoreQuery) All(ctx context.Context, exec boil.ContextExecutor) (KeystoreSlice, error) {
	var o []*Keystore

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Keystore slice")
	}

	return o, nil
}

// Count returns the count of all Keystore records in the query.
func (q keystoreQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count keystore rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q keystoreQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if keystore exists")
	}

	return count > 0, nil
}

// Keystores retrieves all the records using an executor.
func Keystores(mods ...qm.QueryMod) keystoreQuery {
	mods = append(mods, qm.From("\"keystore\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"keystore\".*"})
	}

	return keystoreQuery{q}
}

// FindKeystore retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindKeystore(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Keystore, error) {
	keystoreObj := &Keystore{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"keystore\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, keystoreObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from keystore")
	}

	return keystoreObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Keystore) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no keystore provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(keystoreColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	keystoreInsertCacheMut.RLock()
	cache, cached := keystoreInsertCache[key]
	keystoreInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			keystoreAllColumns,
			keystoreColumnsWithDefault,
			keystoreColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(keystoreType, keystoreMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(keystoreType, keystoreMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"keystore\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"keystore\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into keystore")
	}

	if !cached {
		keystoreInsertCacheMut.Lock()
		keystoreInsertCache[key] = cache
		keystoreInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the Keystore.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Keystore) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	keystoreUpdateCacheMut.RLock()
	cache, cached := keystoreUpdateCache[key]
	keystoreUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			keystoreAllColumns,
			keystorePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update keystore, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"keystore\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, keystorePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(keystoreType, keystoreMapping, append(wl, keystorePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update keystore row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for keystore")
	}

	if !cached {
		keystoreUpdateCacheMut.Lock()
		keystoreUpdateCache[key] = cache
		keystoreUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q keystoreQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for keystore")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for keystore")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o KeystoreSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), keystorePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"keystore\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, keystorePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in keystore slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all keystore")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Keystore) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no keystore provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(keystoreColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	keystoreUpsertCacheMut.RLock()
	cache, cached := keystoreUpsertCache[key]
	keystoreUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			keystoreAllColumns,
			keystoreColumnsWithDefault,
			keystoreColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			keystoreAllColumns,
			keystorePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert keystore, could not build update column list")
		}

		ret := strmangle.SetComplement(keystoreAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(keystorePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert keystore, could not build conflict column list")
			}

			conflict = make([]string, len(keystorePrimaryKeyColumns))
			copy(conflict, keystorePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"keystore\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(keystoreType, keystoreMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(keystoreType, keystoreMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert keystore")
	}

	if !cached {
		keystoreUpsertCacheMut.Lock()
		keystoreUpsertCache[key] = cache
		keystoreUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single Keystore record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Keystore) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Keystore provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), keystorePrimaryKeyMapping)
	sql := "DELETE FROM \"keystore\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from keystore")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for keystore")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q keystoreQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no keystoreQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from keystore")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for keystore")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o KeystoreSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), keystorePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"keystore\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, keystorePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from keystore slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for keystore")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Keystore) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindKeystore(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *KeystoreSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := KeystoreSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), keystorePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"keystore\".* FROM \"keystore\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, keystorePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in KeystoreSlice")
	}

	*o = slice

	return nil
}

// KeystoreExists checks if the Keystore row exists.
func KeystoreExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"keystore\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if keystore exists")
	}

	return exists, nil
}

// Exists checks if the Keystore row exists.
func (o *Keystore) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return KeystoreExists(ctx, exec, o.ID)
}
