// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testKeystores(t *testing.T) {
	t.Parallel()

	query := Keystores()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testKeystoresDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Keystore{}
	if err = randomize.Struct(seed, o, keystoreDBTypes, true, keystoreColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keystore struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Keystores().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testKeystoresQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Keystore{}
	if err = randomize.Struct(seed, o, keystoreDBTypes, true, keystoreColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keystore struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Keystores().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Keystores().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testKeystoresSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Keystore{}
	if err = randomize.Struct(seed, o, keystoreDBTypes, true, keystoreColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keystore struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := KeystoreSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Keystores().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testKeystoresExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Keystore{}
	if err = randomize.Struct(seed, o, keystoreDBTypes, true, keystoreColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keystore struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := KeystoreExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Keystore exists: %s", err)
	}
	if !e {
		t.Errorf("Expected KeystoreExists to return true, but got false.")
	}
}

func testKeystoresFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Keystore{}
	if err = randomize.Struct(seed, o, keystoreDBTypes, true, keystoreColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keystore struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	keystoreFound, err := FindKeystore(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if keystoreFound == nil {
		t.Error("want a record, got nil")
	}
}

func testKeystoresBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Keystore{}
	if err = randomize.Struct(seed, o, keystoreDBTypes, true, keystoreColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keystore struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Keystores().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testKeystoresOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Keystore{}
	if err = randomize.Struct(seed, o, keystoreDBTypes, true, keystoreColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keystore struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Keystores().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testKeystoresAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	keystoreOne := &Keystore{}
	keystoreTwo := &Keystore{}
	if err = randomize.Struct(seed, keystoreOne, keystoreDBTypes, false, keystoreColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keystore struct: %s", err)
	}
	if err = randomize.Struct(seed, keystoreTwo, keystoreDBTypes, false, keystoreColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keystore struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = keystoreOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = keystoreTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Keystores().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testKeystoresCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	keystoreOne := &Keystore{}
	keystoreTwo := &Keystore{}
	if err = randomize.Struct(seed, keystoreOne, keystoreDBTypes, false, keystoreColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keystore struct: %s", err)
	}
	if err = randomize.Struct(seed, keystoreTwo, keystoreDBTypes, false, keystoreColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keystore struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = keystoreOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = keystoreTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Keystores().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testKeystoresInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Keystore{}
	if err = randomize.Struct(seed, o, keystoreDBTypes, true, keystoreColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keystore struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Keystores().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testKeystoresInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Keystore{}
	if err = randomize.Struct(seed, o, keystoreDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Keystore struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(keystorePrimaryKeyColumns, keystoreColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := Keystores().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testKeystoresReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Keystore{}
	if err = randomize.Struct(seed, o, keystoreDBTypes, true, keystoreColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keystore struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testKeystoresReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Keystore{}
	if err = randomize.Struct(seed, o, keystoreDBTypes, true, keystoreColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keystore struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := KeystoreSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testKeystoresSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Keystore{}
	if err = randomize.Struct(seed, o, keystoreDBTypes, true, keystoreColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keystore struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Keystores().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	keystoreDBTypes = map[string]string{`ID`: `uuid`, `KeystoreData`: `jsonb`, `Version`: `integer`, `Cipher`: `character varying`, `KDF`: `character varying`, `DeviceName`: `character varying`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`, `VerificationAddress`: `character varying`}
	_               = bytes.MinRead
)

func testKeystoresUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(keystorePrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(keystoreAllColumns) == len(keystorePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Keystore{}
	if err = randomize.Struct(seed, o, keystoreDBTypes, true, keystoreColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keystore struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Keystores().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, keystoreDBTypes, true, keystorePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Keystore struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testKeystoresSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(keystoreAllColumns) == len(keystorePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Keystore{}
	if err = randomize.Struct(seed, o, keystoreDBTypes, true, keystoreColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Keystore struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Keystores().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, keystoreDBTypes, true, keystorePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Keystore struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(keystoreAllColumns, keystorePrimaryKeyColumns) {
		fields = keystoreAllColumns
	} else {
		fields = strmangle.SetComplement(
			keystoreAllColumns,
			keystorePrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := KeystoreSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testKeystoresUpsert(t *testing.T) {
	t.Parallel()

	if len(keystoreAllColumns) == len(keystorePrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Keystore{}
	if err = randomize.Struct(seed, &o, keystoreDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Keystore struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Keystore: %s", err)
	}

	count, err := Keystores().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, keystoreDBTypes, false, keystorePrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Keystore struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Keystore: %s", err)
	}

	count, err = Keystores().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
