// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("AccessTokens", testAccessTokensUpsert)

	t.Run("AddressIndexes", testAddressIndexesUpsert)

	t.Run("AppUserProfiles", testAppUserProfilesUpsert)

	t.Run("Blocks", testBlocksUpsert)

	t.Run("Chains", testChainsUpsert)

	t.Run("ConfirmationTokens", testConfirmationTokensUpsert)

	t.Run("Credits", testCreditsUpsert)

	t.Run("Keystores", testKeystoresUpsert)

	t.Run("PasswordResetTokens", testPasswordResetTokensUpsert)

	t.Run("PushTokens", testPushTokensUpsert)

	t.Run("RefreshTokens", testRefreshTokensUpsert)

	t.Run("Tokens", testTokensUpsert)

	t.Run("Transactions", testTransactionsUpsert)

	t.Run("Users", testUsersUpsert)

	t.Run("WalletNonces", testWalletNoncesUpsert)

	t.Run("Wallets", testWalletsUpsert)

	t.Run("Withdraws", testWithdrawsUpsert)
}
