// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// WalletNonce is an object representing the database table.
type WalletNonce struct {
	ID         string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	Address    string    `boil:"address" json:"address" toml:"address" yaml:"address"`
	ChainID    int       `boil:"chain_id" json:"chain_id" toml:"chain_id" yaml:"chain_id"`
	Nonce      int       `boil:"nonce" json:"nonce" toml:"nonce" yaml:"nonce"`
	LastUsedAt null.Time `boil:"last_used_at" json:"last_used_at,omitempty" toml:"last_used_at" yaml:"last_used_at,omitempty"`
	CreatedAt  time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt  time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *walletNonceR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L walletNonceL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var WalletNonceColumns = struct {
	ID         string
	Address    string
	ChainID    string
	Nonce      string
	LastUsedAt string
	CreatedAt  string
	UpdatedAt  string
}{
	ID:         "id",
	Address:    "address",
	ChainID:    "chain_id",
	Nonce:      "nonce",
	LastUsedAt: "last_used_at",
	CreatedAt:  "created_at",
	UpdatedAt:  "updated_at",
}

var WalletNonceTableColumns = struct {
	ID         string
	Address    string
	ChainID    string
	Nonce      string
	LastUsedAt string
	CreatedAt  string
	UpdatedAt  string
}{
	ID:         "wallet_nonces.id",
	Address:    "wallet_nonces.address",
	ChainID:    "wallet_nonces.chain_id",
	Nonce:      "wallet_nonces.nonce",
	LastUsedAt: "wallet_nonces.last_used_at",
	CreatedAt:  "wallet_nonces.created_at",
	UpdatedAt:  "wallet_nonces.updated_at",
}

// Generated where

var WalletNonceWhere = struct {
	ID         whereHelperstring
	Address    whereHelperstring
	ChainID    whereHelperint
	Nonce      whereHelperint
	LastUsedAt whereHelpernull_Time
	CreatedAt  whereHelpertime_Time
	UpdatedAt  whereHelpertime_Time
}{
	ID:         whereHelperstring{field: "\"wallet_nonces\".\"id\""},
	Address:    whereHelperstring{field: "\"wallet_nonces\".\"address\""},
	ChainID:    whereHelperint{field: "\"wallet_nonces\".\"chain_id\""},
	Nonce:      whereHelperint{field: "\"wallet_nonces\".\"nonce\""},
	LastUsedAt: whereHelpernull_Time{field: "\"wallet_nonces\".\"last_used_at\""},
	CreatedAt:  whereHelpertime_Time{field: "\"wallet_nonces\".\"created_at\""},
	UpdatedAt:  whereHelpertime_Time{field: "\"wallet_nonces\".\"updated_at\""},
}

// WalletNonceRels is where relationship names are stored.
var WalletNonceRels = struct {
}{}

// walletNonceR is where relationships are stored.
type walletNonceR struct {
}

// NewStruct creates a new relationship struct
func (*walletNonceR) NewStruct() *walletNonceR {
	return &walletNonceR{}
}

// walletNonceL is where Load methods for each relationship are stored.
type walletNonceL struct{}

var (
	walletNonceAllColumns            = []string{"id", "address", "chain_id", "nonce", "last_used_at", "created_at", "updated_at"}
	walletNonceColumnsWithoutDefault = []string{"address", "chain_id"}
	walletNonceColumnsWithDefault    = []string{"id", "nonce", "last_used_at", "created_at", "updated_at"}
	walletNoncePrimaryKeyColumns     = []string{"id"}
	walletNonceGeneratedColumns      = []string{}
)

type (
	// WalletNonceSlice is an alias for a slice of pointers to WalletNonce.
	// This should almost always be used instead of []WalletNonce.
	WalletNonceSlice []*WalletNonce

	walletNonceQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	walletNonceType                 = reflect.TypeOf(&WalletNonce{})
	walletNonceMapping              = queries.MakeStructMapping(walletNonceType)
	walletNoncePrimaryKeyMapping, _ = queries.BindMapping(walletNonceType, walletNonceMapping, walletNoncePrimaryKeyColumns)
	walletNonceInsertCacheMut       sync.RWMutex
	walletNonceInsertCache          = make(map[string]insertCache)
	walletNonceUpdateCacheMut       sync.RWMutex
	walletNonceUpdateCache          = make(map[string]updateCache)
	walletNonceUpsertCacheMut       sync.RWMutex
	walletNonceUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single walletNonce record from the query.
func (q walletNonceQuery) One(ctx context.Context, exec boil.ContextExecutor) (*WalletNonce, error) {
	o := &WalletNonce{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for wallet_nonces")
	}

	return o, nil
}

// All returns all WalletNonce records from the query.
func (q walletNonceQuery) All(ctx context.Context, exec boil.ContextExecutor) (WalletNonceSlice, error) {
	var o []*WalletNonce

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to WalletNonce slice")
	}

	return o, nil
}

// Count returns the count of all WalletNonce records in the query.
func (q walletNonceQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count wallet_nonces rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q walletNonceQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if wallet_nonces exists")
	}

	return count > 0, nil
}

// WalletNonces retrieves all the records using an executor.
func WalletNonces(mods ...qm.QueryMod) walletNonceQuery {
	mods = append(mods, qm.From("\"wallet_nonces\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"wallet_nonces\".*"})
	}

	return walletNonceQuery{q}
}

// FindWalletNonce retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindWalletNonce(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*WalletNonce, error) {
	walletNonceObj := &WalletNonce{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"wallet_nonces\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, walletNonceObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from wallet_nonces")
	}

	return walletNonceObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *WalletNonce) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no wallet_nonces provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(walletNonceColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	walletNonceInsertCacheMut.RLock()
	cache, cached := walletNonceInsertCache[key]
	walletNonceInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			walletNonceAllColumns,
			walletNonceColumnsWithDefault,
			walletNonceColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(walletNonceType, walletNonceMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(walletNonceType, walletNonceMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"wallet_nonces\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"wallet_nonces\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into wallet_nonces")
	}

	if !cached {
		walletNonceInsertCacheMut.Lock()
		walletNonceInsertCache[key] = cache
		walletNonceInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the WalletNonce.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *WalletNonce) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	walletNonceUpdateCacheMut.RLock()
	cache, cached := walletNonceUpdateCache[key]
	walletNonceUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			walletNonceAllColumns,
			walletNoncePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update wallet_nonces, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"wallet_nonces\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, walletNoncePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(walletNonceType, walletNonceMapping, append(wl, walletNoncePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update wallet_nonces row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for wallet_nonces")
	}

	if !cached {
		walletNonceUpdateCacheMut.Lock()
		walletNonceUpdateCache[key] = cache
		walletNonceUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q walletNonceQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for wallet_nonces")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for wallet_nonces")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o WalletNonceSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), walletNoncePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"wallet_nonces\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, walletNoncePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in walletNonce slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all walletNonce")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *WalletNonce) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no wallet_nonces provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(walletNonceColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	walletNonceUpsertCacheMut.RLock()
	cache, cached := walletNonceUpsertCache[key]
	walletNonceUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			walletNonceAllColumns,
			walletNonceColumnsWithDefault,
			walletNonceColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			walletNonceAllColumns,
			walletNoncePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert wallet_nonces, could not build update column list")
		}

		ret := strmangle.SetComplement(walletNonceAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(walletNoncePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert wallet_nonces, could not build conflict column list")
			}

			conflict = make([]string, len(walletNoncePrimaryKeyColumns))
			copy(conflict, walletNoncePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"wallet_nonces\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(walletNonceType, walletNonceMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(walletNonceType, walletNonceMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert wallet_nonces")
	}

	if !cached {
		walletNonceUpsertCacheMut.Lock()
		walletNonceUpsertCache[key] = cache
		walletNonceUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single WalletNonce record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *WalletNonce) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no WalletNonce provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), walletNoncePrimaryKeyMapping)
	sql := "DELETE FROM \"wallet_nonces\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from wallet_nonces")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for wallet_nonces")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q walletNonceQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no walletNonceQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from wallet_nonces")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for wallet_nonces")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o WalletNonceSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), walletNoncePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"wallet_nonces\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, walletNoncePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from walletNonce slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for wallet_nonces")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *WalletNonce) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindWalletNonce(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *WalletNonceSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := WalletNonceSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), walletNoncePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"wallet_nonces\".* FROM \"wallet_nonces\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, walletNoncePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in WalletNonceSlice")
	}

	*o = slice

	return nil
}

// WalletNonceExists checks if the WalletNonce row exists.
func WalletNonceExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"wallet_nonces\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if wallet_nonces exists")
	}

	return exists, nil
}

// Exists checks if the WalletNonce row exists.
func (o *WalletNonce) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return WalletNonceExists(ctx, exec, o.ID)
}
