// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Withdraw is an object representing the database table.
type Withdraw struct {
	ID                   string      `boil:"id" json:"id" toml:"id" yaml:"id"`
	UserID               string      `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	ToAddress            string      `boil:"to_address" json:"to_address" toml:"to_address" yaml:"to_address"`
	FromAddress          null.String `boil:"from_address" json:"from_address,omitempty" toml:"from_address" yaml:"from_address,omitempty"`
	TokenID              int         `boil:"token_id" json:"token_id" toml:"token_id" yaml:"token_id"`
	Amount               string      `boil:"amount" json:"amount" toml:"amount" yaml:"amount"`
	Fee                  string      `boil:"fee" json:"fee" toml:"fee" yaml:"fee"`
	ChainID              int         `boil:"chain_id" json:"chain_id" toml:"chain_id" yaml:"chain_id"`
	ChainType            string      `boil:"chain_type" json:"chain_type" toml:"chain_type" yaml:"chain_type"`
	TXHash               null.String `boil:"tx_hash" json:"tx_hash,omitempty" toml:"tx_hash" yaml:"tx_hash,omitempty"`
	GasPrice             null.String `boil:"gas_price" json:"gas_price,omitempty" toml:"gas_price" yaml:"gas_price,omitempty"`
	MaxFeePerGas         null.String `boil:"max_fee_per_gas" json:"max_fee_per_gas,omitempty" toml:"max_fee_per_gas" yaml:"max_fee_per_gas,omitempty"`
	MaxPriorityFeePerGas null.String `boil:"max_priority_fee_per_gas" json:"max_priority_fee_per_gas,omitempty" toml:"max_priority_fee_per_gas" yaml:"max_priority_fee_per_gas,omitempty"`
	GasUsed              null.String `boil:"gas_used" json:"gas_used,omitempty" toml:"gas_used" yaml:"gas_used,omitempty"`
	Nonce                null.Int    `boil:"nonce" json:"nonce,omitempty" toml:"nonce" yaml:"nonce,omitempty"`
	Status               string      `boil:"status" json:"status" toml:"status" yaml:"status"`
	ErrorMessage         null.String `boil:"error_message" json:"error_message,omitempty" toml:"error_message" yaml:"error_message,omitempty"`
	OperationID          null.String `boil:"operation_id" json:"operation_id,omitempty" toml:"operation_id" yaml:"operation_id,omitempty"`
	CreatedAt            time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt            time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *withdrawR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L withdrawL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var WithdrawColumns = struct {
	ID                   string
	UserID               string
	ToAddress            string
	FromAddress          string
	TokenID              string
	Amount               string
	Fee                  string
	ChainID              string
	ChainType            string
	TXHash               string
	GasPrice             string
	MaxFeePerGas         string
	MaxPriorityFeePerGas string
	GasUsed              string
	Nonce                string
	Status               string
	ErrorMessage         string
	OperationID          string
	CreatedAt            string
	UpdatedAt            string
}{
	ID:                   "id",
	UserID:               "user_id",
	ToAddress:            "to_address",
	FromAddress:          "from_address",
	TokenID:              "token_id",
	Amount:               "amount",
	Fee:                  "fee",
	ChainID:              "chain_id",
	ChainType:            "chain_type",
	TXHash:               "tx_hash",
	GasPrice:             "gas_price",
	MaxFeePerGas:         "max_fee_per_gas",
	MaxPriorityFeePerGas: "max_priority_fee_per_gas",
	GasUsed:              "gas_used",
	Nonce:                "nonce",
	Status:               "status",
	ErrorMessage:         "error_message",
	OperationID:          "operation_id",
	CreatedAt:            "created_at",
	UpdatedAt:            "updated_at",
}

var WithdrawTableColumns = struct {
	ID                   string
	UserID               string
	ToAddress            string
	FromAddress          string
	TokenID              string
	Amount               string
	Fee                  string
	ChainID              string
	ChainType            string
	TXHash               string
	GasPrice             string
	MaxFeePerGas         string
	MaxPriorityFeePerGas string
	GasUsed              string
	Nonce                string
	Status               string
	ErrorMessage         string
	OperationID          string
	CreatedAt            string
	UpdatedAt            string
}{
	ID:                   "withdraws.id",
	UserID:               "withdraws.user_id",
	ToAddress:            "withdraws.to_address",
	FromAddress:          "withdraws.from_address",
	TokenID:              "withdraws.token_id",
	Amount:               "withdraws.amount",
	Fee:                  "withdraws.fee",
	ChainID:              "withdraws.chain_id",
	ChainType:            "withdraws.chain_type",
	TXHash:               "withdraws.tx_hash",
	GasPrice:             "withdraws.gas_price",
	MaxFeePerGas:         "withdraws.max_fee_per_gas",
	MaxPriorityFeePerGas: "withdraws.max_priority_fee_per_gas",
	GasUsed:              "withdraws.gas_used",
	Nonce:                "withdraws.nonce",
	Status:               "withdraws.status",
	ErrorMessage:         "withdraws.error_message",
	OperationID:          "withdraws.operation_id",
	CreatedAt:            "withdraws.created_at",
	UpdatedAt:            "withdraws.updated_at",
}

// Generated where

var WithdrawWhere = struct {
	ID                   whereHelperstring
	UserID               whereHelperstring
	ToAddress            whereHelperstring
	FromAddress          whereHelpernull_String
	TokenID              whereHelperint
	Amount               whereHelperstring
	Fee                  whereHelperstring
	ChainID              whereHelperint
	ChainType            whereHelperstring
	TXHash               whereHelpernull_String
	GasPrice             whereHelpernull_String
	MaxFeePerGas         whereHelpernull_String
	MaxPriorityFeePerGas whereHelpernull_String
	GasUsed              whereHelpernull_String
	Nonce                whereHelpernull_Int
	Status               whereHelperstring
	ErrorMessage         whereHelpernull_String
	OperationID          whereHelpernull_String
	CreatedAt            whereHelpertime_Time
	UpdatedAt            whereHelpertime_Time
}{
	ID:                   whereHelperstring{field: "\"withdraws\".\"id\""},
	UserID:               whereHelperstring{field: "\"withdraws\".\"user_id\""},
	ToAddress:            whereHelperstring{field: "\"withdraws\".\"to_address\""},
	FromAddress:          whereHelpernull_String{field: "\"withdraws\".\"from_address\""},
	TokenID:              whereHelperint{field: "\"withdraws\".\"token_id\""},
	Amount:               whereHelperstring{field: "\"withdraws\".\"amount\""},
	Fee:                  whereHelperstring{field: "\"withdraws\".\"fee\""},
	ChainID:              whereHelperint{field: "\"withdraws\".\"chain_id\""},
	ChainType:            whereHelperstring{field: "\"withdraws\".\"chain_type\""},
	TXHash:               whereHelpernull_String{field: "\"withdraws\".\"tx_hash\""},
	GasPrice:             whereHelpernull_String{field: "\"withdraws\".\"gas_price\""},
	MaxFeePerGas:         whereHelpernull_String{field: "\"withdraws\".\"max_fee_per_gas\""},
	MaxPriorityFeePerGas: whereHelpernull_String{field: "\"withdraws\".\"max_priority_fee_per_gas\""},
	GasUsed:              whereHelpernull_String{field: "\"withdraws\".\"gas_used\""},
	Nonce:                whereHelpernull_Int{field: "\"withdraws\".\"nonce\""},
	Status:               whereHelperstring{field: "\"withdraws\".\"status\""},
	ErrorMessage:         whereHelpernull_String{field: "\"withdraws\".\"error_message\""},
	OperationID:          whereHelpernull_String{field: "\"withdraws\".\"operation_id\""},
	CreatedAt:            whereHelpertime_Time{field: "\"withdraws\".\"created_at\""},
	UpdatedAt:            whereHelpertime_Time{field: "\"withdraws\".\"updated_at\""},
}

// WithdrawRels is where relationship names are stored.
var WithdrawRels = struct {
	Token string
	User  string
}{
	Token: "Token",
	User:  "User",
}

// withdrawR is where relationships are stored.
type withdrawR struct {
	Token *Token `boil:"Token" json:"Token" toml:"Token" yaml:"Token"`
	User  *User  `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*withdrawR) NewStruct() *withdrawR {
	return &withdrawR{}
}

func (o *Withdraw) GetToken() *Token {
	if o == nil {
		return nil
	}

	return o.R.GetToken()
}

func (r *withdrawR) GetToken() *Token {
	if r == nil {
		return nil
	}

	return r.Token
}

func (o *Withdraw) GetUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetUser()
}

func (r *withdrawR) GetUser() *User {
	if r == nil {
		return nil
	}

	return r.User
}

// withdrawL is where Load methods for each relationship are stored.
type withdrawL struct{}

var (
	withdrawAllColumns            = []string{"id", "user_id", "to_address", "from_address", "token_id", "amount", "fee", "chain_id", "chain_type", "tx_hash", "gas_price", "max_fee_per_gas", "max_priority_fee_per_gas", "gas_used", "nonce", "status", "error_message", "operation_id", "created_at", "updated_at"}
	withdrawColumnsWithoutDefault = []string{"user_id", "to_address", "token_id", "amount", "fee", "chain_id", "chain_type", "status"}
	withdrawColumnsWithDefault    = []string{"id", "from_address", "tx_hash", "gas_price", "max_fee_per_gas", "max_priority_fee_per_gas", "gas_used", "nonce", "error_message", "operation_id", "created_at", "updated_at"}
	withdrawPrimaryKeyColumns     = []string{"id"}
	withdrawGeneratedColumns      = []string{}
)

type (
	// WithdrawSlice is an alias for a slice of pointers to Withdraw.
	// This should almost always be used instead of []Withdraw.
	WithdrawSlice []*Withdraw

	withdrawQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	withdrawType                 = reflect.TypeOf(&Withdraw{})
	withdrawMapping              = queries.MakeStructMapping(withdrawType)
	withdrawPrimaryKeyMapping, _ = queries.BindMapping(withdrawType, withdrawMapping, withdrawPrimaryKeyColumns)
	withdrawInsertCacheMut       sync.RWMutex
	withdrawInsertCache          = make(map[string]insertCache)
	withdrawUpdateCacheMut       sync.RWMutex
	withdrawUpdateCache          = make(map[string]updateCache)
	withdrawUpsertCacheMut       sync.RWMutex
	withdrawUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single withdraw record from the query.
func (q withdrawQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Withdraw, error) {
	o := &Withdraw{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for withdraws")
	}

	return o, nil
}

// All returns all Withdraw records from the query.
func (q withdrawQuery) All(ctx context.Context, exec boil.ContextExecutor) (WithdrawSlice, error) {
	var o []*Withdraw

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Withdraw slice")
	}

	return o, nil
}

// Count returns the count of all Withdraw records in the query.
func (q withdrawQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count withdraws rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q withdrawQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if withdraws exists")
	}

	return count > 0, nil
}

// Token pointed to by the foreign key.
func (o *Withdraw) Token(mods ...qm.QueryMod) tokenQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.TokenID),
	}

	queryMods = append(queryMods, mods...)

	return Tokens(queryMods...)
}

// User pointed to by the foreign key.
func (o *Withdraw) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadToken allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (withdrawL) LoadToken(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWithdraw interface{}, mods queries.Applicator) error {
	var slice []*Withdraw
	var object *Withdraw

	if singular {
		var ok bool
		object, ok = maybeWithdraw.(*Withdraw)
		if !ok {
			object = new(Withdraw)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWithdraw)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWithdraw))
			}
		}
	} else {
		s, ok := maybeWithdraw.(*[]*Withdraw)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWithdraw)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWithdraw))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &withdrawR{}
		}
		args[object.TokenID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &withdrawR{}
			}

			args[obj.TokenID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`tokens`),
		qm.WhereIn(`tokens.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Token")
	}

	var resultSlice []*Token
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Token")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for tokens")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for tokens")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Token = foreign
		if foreign.R == nil {
			foreign.R = &tokenR{}
		}
		foreign.R.Withdraws = append(foreign.R.Withdraws, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.TokenID == foreign.ID {
				local.R.Token = foreign
				if foreign.R == nil {
					foreign.R = &tokenR{}
				}
				foreign.R.Withdraws = append(foreign.R.Withdraws, local)
				break
			}
		}
	}

	return nil
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (withdrawL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeWithdraw interface{}, mods queries.Applicator) error {
	var slice []*Withdraw
	var object *Withdraw

	if singular {
		var ok bool
		object, ok = maybeWithdraw.(*Withdraw)
		if !ok {
			object = new(Withdraw)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeWithdraw)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeWithdraw))
			}
		}
	} else {
		s, ok := maybeWithdraw.(*[]*Withdraw)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeWithdraw)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeWithdraw))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &withdrawR{}
		}
		args[object.UserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &withdrawR{}
			}

			args[obj.UserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.Withdraws = append(foreign.R.Withdraws, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.Withdraws = append(foreign.R.Withdraws, local)
				break
			}
		}
	}

	return nil
}

// SetToken of the withdraw to the related item.
// Sets o.R.Token to related.
// Adds o to related.R.Withdraws.
func (o *Withdraw) SetToken(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Token) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"withdraws\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"token_id"}),
		strmangle.WhereClause("\"", "\"", 2, withdrawPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.TokenID = related.ID
	if o.R == nil {
		o.R = &withdrawR{
			Token: related,
		}
	} else {
		o.R.Token = related
	}

	if related.R == nil {
		related.R = &tokenR{
			Withdraws: WithdrawSlice{o},
		}
	} else {
		related.R.Withdraws = append(related.R.Withdraws, o)
	}

	return nil
}

// SetUser of the withdraw to the related item.
// Sets o.R.User to related.
// Adds o to related.R.Withdraws.
func (o *Withdraw) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"withdraws\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, withdrawPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &withdrawR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			Withdraws: WithdrawSlice{o},
		}
	} else {
		related.R.Withdraws = append(related.R.Withdraws, o)
	}

	return nil
}

// Withdraws retrieves all the records using an executor.
func Withdraws(mods ...qm.QueryMod) withdrawQuery {
	mods = append(mods, qm.From("\"withdraws\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"withdraws\".*"})
	}

	return withdrawQuery{q}
}

// FindWithdraw retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindWithdraw(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*Withdraw, error) {
	withdrawObj := &Withdraw{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"withdraws\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, withdrawObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from withdraws")
	}

	return withdrawObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Withdraw) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no withdraws provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(withdrawColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	withdrawInsertCacheMut.RLock()
	cache, cached := withdrawInsertCache[key]
	withdrawInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			withdrawAllColumns,
			withdrawColumnsWithDefault,
			withdrawColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(withdrawType, withdrawMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(withdrawType, withdrawMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"withdraws\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"withdraws\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into withdraws")
	}

	if !cached {
		withdrawInsertCacheMut.Lock()
		withdrawInsertCache[key] = cache
		withdrawInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the Withdraw.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Withdraw) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	withdrawUpdateCacheMut.RLock()
	cache, cached := withdrawUpdateCache[key]
	withdrawUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			withdrawAllColumns,
			withdrawPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update withdraws, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"withdraws\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, withdrawPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(withdrawType, withdrawMapping, append(wl, withdrawPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update withdraws row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for withdraws")
	}

	if !cached {
		withdrawUpdateCacheMut.Lock()
		withdrawUpdateCache[key] = cache
		withdrawUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q withdrawQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for withdraws")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for withdraws")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o WithdrawSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), withdrawPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"withdraws\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, withdrawPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in withdraw slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all withdraw")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Withdraw) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no withdraws provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(withdrawColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	withdrawUpsertCacheMut.RLock()
	cache, cached := withdrawUpsertCache[key]
	withdrawUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			withdrawAllColumns,
			withdrawColumnsWithDefault,
			withdrawColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			withdrawAllColumns,
			withdrawPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert withdraws, could not build update column list")
		}

		ret := strmangle.SetComplement(withdrawAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(withdrawPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert withdraws, could not build conflict column list")
			}

			conflict = make([]string, len(withdrawPrimaryKeyColumns))
			copy(conflict, withdrawPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"withdraws\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(withdrawType, withdrawMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(withdrawType, withdrawMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert withdraws")
	}

	if !cached {
		withdrawUpsertCacheMut.Lock()
		withdrawUpsertCache[key] = cache
		withdrawUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single Withdraw record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Withdraw) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Withdraw provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), withdrawPrimaryKeyMapping)
	sql := "DELETE FROM \"withdraws\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from withdraws")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for withdraws")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q withdrawQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no withdrawQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from withdraws")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for withdraws")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o WithdrawSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), withdrawPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"withdraws\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, withdrawPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from withdraw slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for withdraws")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Withdraw) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindWithdraw(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *WithdrawSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := WithdrawSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), withdrawPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"withdraws\".* FROM \"withdraws\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, withdrawPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in WithdrawSlice")
	}

	*o = slice

	return nil
}

// WithdrawExists checks if the Withdraw row exists.
func WithdrawExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"withdraws\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if withdraws exists")
	}

	return exists, nil
}

// Exists checks if the Withdraw row exists.
func (o *Withdraw) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return WithdrawExists(ctx, exec, o.ID)
}
