// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"bytes"
	"context"
	"reflect"
	"testing"

	"github.com/aarondl/randomize"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/strmangle"
)

var (
	// Relationships sometimes use the reflection helper queries.Equal/queries.Assign
	// so force a package dependency in case they don't.
	_ = queries.Equal
)

func testWithdraws(t *testing.T) {
	t.Parallel()

	query := Withdraws()

	if query.Query == nil {
		t.Error("expected a query, got nothing")
	}
}

func testWithdrawsDelete(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Withdraw{}
	if err = randomize.Struct(seed, o, withdrawDBTypes, true, withdrawColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Withdraw struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := o.Delete(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Withdraws().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWithdrawsQueryDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Withdraw{}
	if err = randomize.Struct(seed, o, withdrawDBTypes, true, withdrawColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Withdraw struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if rowsAff, err := Withdraws().DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Withdraws().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWithdrawsSliceDeleteAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Withdraw{}
	if err = randomize.Struct(seed, o, withdrawDBTypes, true, withdrawColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Withdraw struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := WithdrawSlice{o}

	if rowsAff, err := slice.DeleteAll(ctx, tx); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only have deleted one row, but affected:", rowsAff)
	}

	count, err := Withdraws().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 0 {
		t.Error("want zero records, got:", count)
	}
}

func testWithdrawsExists(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Withdraw{}
	if err = randomize.Struct(seed, o, withdrawDBTypes, true, withdrawColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Withdraw struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	e, err := WithdrawExists(ctx, tx, o.ID)
	if err != nil {
		t.Errorf("Unable to check if Withdraw exists: %s", err)
	}
	if !e {
		t.Errorf("Expected WithdrawExists to return true, but got false.")
	}
}

func testWithdrawsFind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Withdraw{}
	if err = randomize.Struct(seed, o, withdrawDBTypes, true, withdrawColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Withdraw struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	withdrawFound, err := FindWithdraw(ctx, tx, o.ID)
	if err != nil {
		t.Error(err)
	}

	if withdrawFound == nil {
		t.Error("want a record, got nil")
	}
}

func testWithdrawsBind(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Withdraw{}
	if err = randomize.Struct(seed, o, withdrawDBTypes, true, withdrawColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Withdraw struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = Withdraws().Bind(ctx, tx, o); err != nil {
		t.Error(err)
	}
}

func testWithdrawsOne(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Withdraw{}
	if err = randomize.Struct(seed, o, withdrawDBTypes, true, withdrawColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Withdraw struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if x, err := Withdraws().One(ctx, tx); err != nil {
		t.Error(err)
	} else if x == nil {
		t.Error("expected to get a non nil record")
	}
}

func testWithdrawsAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	withdrawOne := &Withdraw{}
	withdrawTwo := &Withdraw{}
	if err = randomize.Struct(seed, withdrawOne, withdrawDBTypes, false, withdrawColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Withdraw struct: %s", err)
	}
	if err = randomize.Struct(seed, withdrawTwo, withdrawDBTypes, false, withdrawColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Withdraw struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = withdrawOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = withdrawTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Withdraws().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 2 {
		t.Error("want 2 records, got:", len(slice))
	}
}

func testWithdrawsCount(t *testing.T) {
	t.Parallel()

	var err error
	seed := randomize.NewSeed()
	withdrawOne := &Withdraw{}
	withdrawTwo := &Withdraw{}
	if err = randomize.Struct(seed, withdrawOne, withdrawDBTypes, false, withdrawColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Withdraw struct: %s", err)
	}
	if err = randomize.Struct(seed, withdrawTwo, withdrawDBTypes, false, withdrawColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Withdraw struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = withdrawOne.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}
	if err = withdrawTwo.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Withdraws().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 2 {
		t.Error("want 2 records, got:", count)
	}
}

func testWithdrawsInsert(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Withdraw{}
	if err = randomize.Struct(seed, o, withdrawDBTypes, true, withdrawColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Withdraw struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Withdraws().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testWithdrawsInsertWhitelist(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Withdraw{}
	if err = randomize.Struct(seed, o, withdrawDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Withdraw struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Whitelist(strmangle.SetMerge(withdrawPrimaryKeyColumns, withdrawColumnsWithoutDefault)...)); err != nil {
		t.Error(err)
	}

	count, err := Withdraws().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}
}

func testWithdrawToOneTokenUsingToken(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Withdraw
	var foreign Token

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, withdrawDBTypes, false, withdrawColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Withdraw struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, tokenDBTypes, false, tokenColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Token struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.TokenID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.Token().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := WithdrawSlice{&local}
	if err = local.L.LoadToken(ctx, tx, false, (*[]*Withdraw)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Token == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.Token = nil
	if err = local.L.LoadToken(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.Token == nil {
		t.Error("struct should have been eager loaded")
	}

}

func testWithdrawToOneUserUsingUser(t *testing.T) {
	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var local Withdraw
	var foreign User

	seed := randomize.NewSeed()
	if err := randomize.Struct(seed, &local, withdrawDBTypes, false, withdrawColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Withdraw struct: %s", err)
	}
	if err := randomize.Struct(seed, &foreign, userDBTypes, false, userColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize User struct: %s", err)
	}

	if err := foreign.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	local.UserID = foreign.ID
	if err := local.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	check, err := local.User().One(ctx, tx)
	if err != nil {
		t.Fatal(err)
	}

	if check.ID != foreign.ID {
		t.Errorf("want: %v, got %v", foreign.ID, check.ID)
	}

	slice := WithdrawSlice{&local}
	if err = local.L.LoadUser(ctx, tx, false, (*[]*Withdraw)(&slice), nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

	local.R.User = nil
	if err = local.L.LoadUser(ctx, tx, true, &local, nil); err != nil {
		t.Fatal(err)
	}
	if local.R.User == nil {
		t.Error("struct should have been eager loaded")
	}

}

func testWithdrawToOneSetOpTokenUsingToken(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Withdraw
	var b, c Token

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, withdrawDBTypes, false, strmangle.SetComplement(withdrawPrimaryKeyColumns, withdrawColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, tokenDBTypes, false, strmangle.SetComplement(tokenPrimaryKeyColumns, tokenColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, tokenDBTypes, false, strmangle.SetComplement(tokenPrimaryKeyColumns, tokenColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*Token{&b, &c} {
		err = a.SetToken(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.Token != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Withdraws[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.TokenID != x.ID {
			t.Error("foreign key was wrong value", a.TokenID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.TokenID))
		reflect.Indirect(reflect.ValueOf(&a.TokenID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.TokenID != x.ID {
			t.Error("foreign key was wrong value", a.TokenID, x.ID)
		}
	}
}
func testWithdrawToOneSetOpUserUsingUser(t *testing.T) {
	var err error

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()

	var a Withdraw
	var b, c User

	seed := randomize.NewSeed()
	if err = randomize.Struct(seed, &a, withdrawDBTypes, false, strmangle.SetComplement(withdrawPrimaryKeyColumns, withdrawColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &b, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}
	if err = randomize.Struct(seed, &c, userDBTypes, false, strmangle.SetComplement(userPrimaryKeyColumns, userColumnsWithoutDefault)...); err != nil {
		t.Fatal(err)
	}

	if err := a.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}
	if err = b.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Fatal(err)
	}

	for i, x := range []*User{&b, &c} {
		err = a.SetUser(ctx, tx, i != 0, x)
		if err != nil {
			t.Fatal(err)
		}

		if a.R.User != x {
			t.Error("relationship struct not set to correct value")
		}

		if x.R.Withdraws[0] != &a {
			t.Error("failed to append to foreign relationship struct")
		}
		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID)
		}

		zero := reflect.Zero(reflect.TypeOf(a.UserID))
		reflect.Indirect(reflect.ValueOf(&a.UserID)).Set(zero)

		if err = a.Reload(ctx, tx); err != nil {
			t.Fatal("failed to reload", err)
		}

		if a.UserID != x.ID {
			t.Error("foreign key was wrong value", a.UserID, x.ID)
		}
	}
}

func testWithdrawsReload(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Withdraw{}
	if err = randomize.Struct(seed, o, withdrawDBTypes, true, withdrawColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Withdraw struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	if err = o.Reload(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testWithdrawsReloadAll(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Withdraw{}
	if err = randomize.Struct(seed, o, withdrawDBTypes, true, withdrawColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Withdraw struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice := WithdrawSlice{o}

	if err = slice.ReloadAll(ctx, tx); err != nil {
		t.Error(err)
	}
}

func testWithdrawsSelect(t *testing.T) {
	t.Parallel()

	seed := randomize.NewSeed()
	var err error
	o := &Withdraw{}
	if err = randomize.Struct(seed, o, withdrawDBTypes, true, withdrawColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Withdraw struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	slice, err := Withdraws().All(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if len(slice) != 1 {
		t.Error("want one record, got:", len(slice))
	}
}

var (
	withdrawDBTypes = map[string]string{`ID`: `uuid`, `UserID`: `uuid`, `ToAddress`: `character varying`, `FromAddress`: `character varying`, `TokenID`: `integer`, `Amount`: `text`, `Fee`: `text`, `ChainID`: `integer`, `ChainType`: `character varying`, `TXHash`: `character varying`, `GasPrice`: `text`, `MaxFeePerGas`: `text`, `MaxPriorityFeePerGas`: `text`, `GasUsed`: `text`, `Nonce`: `integer`, `Status`: `enum.withdraw_status('user_withdraw_request','signing','pending','processing','confirmed','failed')`, `ErrorMessage`: `text`, `OperationID`: `uuid`, `CreatedAt`: `timestamp with time zone`, `UpdatedAt`: `timestamp with time zone`}
	_               = bytes.MinRead
)

func testWithdrawsUpdate(t *testing.T) {
	t.Parallel()

	if 0 == len(withdrawPrimaryKeyColumns) {
		t.Skip("Skipping table with no primary key columns")
	}
	if len(withdrawAllColumns) == len(withdrawPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Withdraw{}
	if err = randomize.Struct(seed, o, withdrawDBTypes, true, withdrawColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Withdraw struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Withdraws().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, withdrawDBTypes, true, withdrawPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Withdraw struct: %s", err)
	}

	if rowsAff, err := o.Update(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("should only affect one row but affected", rowsAff)
	}
}

func testWithdrawsSliceUpdateAll(t *testing.T) {
	t.Parallel()

	if len(withdrawAllColumns) == len(withdrawPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	o := &Withdraw{}
	if err = randomize.Struct(seed, o, withdrawDBTypes, true, withdrawColumnsWithDefault...); err != nil {
		t.Errorf("Unable to randomize Withdraw struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Insert(ctx, tx, boil.Infer()); err != nil {
		t.Error(err)
	}

	count, err := Withdraws().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}

	if count != 1 {
		t.Error("want one record, got:", count)
	}

	if err = randomize.Struct(seed, o, withdrawDBTypes, true, withdrawPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Withdraw struct: %s", err)
	}

	// Remove Primary keys and unique columns from what we plan to update
	var fields []string
	if strmangle.StringSliceMatch(withdrawAllColumns, withdrawPrimaryKeyColumns) {
		fields = withdrawAllColumns
	} else {
		fields = strmangle.SetComplement(
			withdrawAllColumns,
			withdrawPrimaryKeyColumns,
		)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	typ := reflect.TypeOf(o).Elem()
	n := typ.NumField()

	updateMap := M{}
	for _, col := range fields {
		for i := 0; i < n; i++ {
			f := typ.Field(i)
			if f.Tag.Get("boil") == col {
				updateMap[col] = value.Field(i).Interface()
			}
		}
	}

	slice := WithdrawSlice{o}
	if rowsAff, err := slice.UpdateAll(ctx, tx, updateMap); err != nil {
		t.Error(err)
	} else if rowsAff != 1 {
		t.Error("wanted one record updated but got", rowsAff)
	}
}

func testWithdrawsUpsert(t *testing.T) {
	t.Parallel()

	if len(withdrawAllColumns) == len(withdrawPrimaryKeyColumns) {
		t.Skip("Skipping table with only primary key columns")
	}

	seed := randomize.NewSeed()
	var err error
	// Attempt the INSERT side of an UPSERT
	o := Withdraw{}
	if err = randomize.Struct(seed, &o, withdrawDBTypes, true); err != nil {
		t.Errorf("Unable to randomize Withdraw struct: %s", err)
	}

	ctx := context.Background()
	tx := MustTx(boil.BeginTx(ctx, nil))
	defer func() { _ = tx.Rollback() }()
	if err = o.Upsert(ctx, tx, false, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Withdraw: %s", err)
	}

	count, err := Withdraws().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}

	// Attempt the UPDATE side of an UPSERT
	if err = randomize.Struct(seed, &o, withdrawDBTypes, false, withdrawPrimaryKeyColumns...); err != nil {
		t.Errorf("Unable to randomize Withdraw struct: %s", err)
	}

	if err = o.Upsert(ctx, tx, true, nil, boil.Infer(), boil.Infer()); err != nil {
		t.Errorf("Unable to upsert Withdraw: %s", err)
	}

	count, err = Withdraws().Count(ctx, tx)
	if err != nil {
		t.Error(err)
	}
	if count != 1 {
		t.Error("want one record, got:", count)
	}
}
