// Code generated by go-swagger; DO NOT EDIT.

package wallet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewGetWalletAddressRouteParams creates a new GetWalletAddressRouteParams object
// no default values defined in spec.
func NewGetWalletAddressRouteParams() GetWalletAddressRouteParams {

	return GetWalletAddressRouteParams{}
}

// GetWalletAddressRouteParams contains all the bound params for the get wallet address route operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetWalletAddressRoute
type GetWalletAddressRouteParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Chain ID (1 for Ethereum Mainnet, 137 for Polygon, 56 for BSC, etc.)
	  Required: true
	  In: query
	*/
	ChainID int64 `query:"chain_id"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetWalletAddressRouteParams() beforehand.
func (o *GetWalletAddressRouteParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qChainID, qhkChainID, _ := qs.GetOK("chain_id")
	if err := o.bindChainID(qChainID, qhkChainID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetWalletAddressRouteParams) Validate(formats strfmt.Registry) error {
	var res []error

	// chain_id
	// Required: true
	// AllowEmptyValue: false
	if err := validate.Required("chain_id", "query", o.ChainID); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindChainID binds and validates parameter ChainID from query.
func (o *GetWalletAddressRouteParams) bindChainID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	if !hasKey {
		return errors.Required("chain_id", "query", rawData)
	}
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// AllowEmptyValue: false
	if err := validate.RequiredString("chain_id", "query", raw); err != nil {
		return err
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("chain_id", "query", "int64", raw)
	}
	o.ChainID = value

	return nil
}
