// Code generated by go-swagger; DO NOT EDIT.

package wallet

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// NewGetWithdrawsRouteParams creates a new GetWithdrawsRouteParams object
// with the default values initialized.
func NewGetWithdrawsRouteParams() GetWithdrawsRouteParams {

	var (
		// initialize parameters with default values

		limitDefault  = int64(50)
		offsetDefault = int64(0)
	)

	return GetWithdrawsRouteParams{
		Limit: &limitDefault,

		Offset: &offsetDefault,
	}
}

// GetWithdrawsRouteParams contains all the bound params for the get withdraws route operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetWithdrawsRoute
type GetWithdrawsRouteParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Chain ID
	  In: query
	*/
	ChainID *int64 `query:"chain_id"`
	/*Limit used for pagination, number of records to retrieve
	  Maximum: 500
	  Minimum: 1
	  In: query
	  Default: 50
	*/
	Limit *int64 `query:"limit"`
	/*Offset used for pagination, number of records to skip
	  Minimum: 0
	  In: query
	  Default: 0
	*/
	Offset *int64 `query:"offset"`
	/*Filter by status
	  In: query
	*/
	Status *string `query:"status"`
	/*Token ID
	  In: query
	*/
	TokenID *int64 `query:"token_id"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetWithdrawsRouteParams() beforehand.
func (o *GetWithdrawsRouteParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qChainID, qhkChainID, _ := qs.GetOK("chain_id")
	if err := o.bindChainID(qChainID, qhkChainID, route.Formats); err != nil {
		res = append(res, err)
	}

	qLimit, qhkLimit, _ := qs.GetOK("limit")
	if err := o.bindLimit(qLimit, qhkLimit, route.Formats); err != nil {
		res = append(res, err)
	}

	qOffset, qhkOffset, _ := qs.GetOK("offset")
	if err := o.bindOffset(qOffset, qhkOffset, route.Formats); err != nil {
		res = append(res, err)
	}

	qStatus, qhkStatus, _ := qs.GetOK("status")
	if err := o.bindStatus(qStatus, qhkStatus, route.Formats); err != nil {
		res = append(res, err)
	}

	qTokenID, qhkTokenID, _ := qs.GetOK("token_id")
	if err := o.bindTokenID(qTokenID, qhkTokenID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *GetWithdrawsRouteParams) Validate(formats strfmt.Registry) error {
	var res []error

	// chain_id
	// Required: false
	// AllowEmptyValue: false

	// limit
	// Required: false
	// AllowEmptyValue: false

	if err := o.validateLimit(formats); err != nil {
		res = append(res, err)
	}

	// offset
	// Required: false
	// AllowEmptyValue: false

	if err := o.validateOffset(formats); err != nil {
		res = append(res, err)
	}

	// status
	// Required: false
	// AllowEmptyValue: false

	// token_id
	// Required: false
	// AllowEmptyValue: false

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindChainID binds and validates parameter ChainID from query.
func (o *GetWithdrawsRouteParams) bindChainID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("chain_id", "query", "int64", raw)
	}
	o.ChainID = &value

	return nil
}

// bindLimit binds and validates parameter Limit from query.
func (o *GetWithdrawsRouteParams) bindLimit(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetWithdrawsRouteParams()
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("limit", "query", "int64", raw)
	}
	o.Limit = &value

	if err := o.validateLimit(formats); err != nil {
		return err
	}

	return nil
}

// validateLimit carries on validations for parameter Limit
func (o *GetWithdrawsRouteParams) validateLimit(formats strfmt.Registry) error {

	// Required: false
	if o.Limit == nil {
		return nil
	}

	if err := validate.MinimumInt("limit", "query", *o.Limit, 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("limit", "query", *o.Limit, 500, false); err != nil {
		return err
	}

	return nil
}

// bindOffset binds and validates parameter Offset from query.
func (o *GetWithdrawsRouteParams) bindOffset(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		// Default values have been previously initialized by NewGetWithdrawsRouteParams()
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("offset", "query", "int64", raw)
	}
	o.Offset = &value

	if err := o.validateOffset(formats); err != nil {
		return err
	}

	return nil
}

// validateOffset carries on validations for parameter Offset
func (o *GetWithdrawsRouteParams) validateOffset(formats strfmt.Registry) error {

	// Required: false
	if o.Offset == nil {
		return nil
	}

	if err := validate.MinimumInt("offset", "query", *o.Offset, 0, false); err != nil {
		return err
	}

	return nil
}

// bindStatus binds and validates parameter Status from query.
func (o *GetWithdrawsRouteParams) bindStatus(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	o.Status = &raw

	return nil
}

// bindTokenID binds and validates parameter TokenID from query.
func (o *GetWithdrawsRouteParams) bindTokenID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false
	if raw == "" { // empty values pass all other validations
		return nil
	}

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("token_id", "query", "int64", raw)
	}
	o.TokenID = &value

	return nil
}
